/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables;


import me.mykindos.betterpvp.balancesim.database.jooq.Indexes;
import me.mykindos.betterpvp.balancesim.database.jooq.Keys;
import me.mykindos.betterpvp.balancesim.database.jooq.Public;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimResult.SimResultPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun.SimRunPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimTrace.SimTracePath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.records.SimBuildRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimBuild extends TableImpl<SimBuildRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sim_build</code>
     */
    public static final SimBuild SIM_BUILD = new SimBuild();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimBuildRecord> getRecordType() {
        return SimBuildRecord.class;
    }

    /**
     * The column <code>public.sim_build.id</code>.
     */
    public final TableField<SimBuildRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sim_build.run_id</code>.
     */
    public final TableField<SimBuildRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_build.role</code>.
     */
    public final TableField<SimBuildRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_build.weapon</code>.
     */
    public final TableField<SimBuildRecord, String> WEAPON = createField(DSL.name("weapon"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_build.runes</code>.
     */
    public final TableField<SimBuildRecord, JSONB> RUNES = createField(DSL.name("runes"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.sim_build.skills</code>.
     */
    public final TableField<SimBuildRecord, JSONB> SKILLS = createField(DSL.name("skills"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.sim_build.points_spent</code>.
     */
    public final TableField<SimBuildRecord, Integer> POINTS_SPENT = createField(DSL.name("points_spent"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_build.booster</code>.
     */
    public final TableField<SimBuildRecord, Boolean> BOOSTER = createField(DSL.name("booster"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.sim_build.fingerprint</code>.
     */
    public final TableField<SimBuildRecord, String> FINGERPRINT = createField(DSL.name("fingerprint"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_build.weapon_damage_base</code>.
     */
    public final TableField<SimBuildRecord, BigDecimal> WEAPON_DAMAGE_BASE = createField(DSL.name("weapon_damage_base"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_build.weapon_damage_min</code>.
     */
    public final TableField<SimBuildRecord, BigDecimal> WEAPON_DAMAGE_MIN = createField(DSL.name("weapon_damage_min"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_build.weapon_damage_max</code>.
     */
    public final TableField<SimBuildRecord, BigDecimal> WEAPON_DAMAGE_MAX = createField(DSL.name("weapon_damage_max"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_build.weapon_attack_speed_base</code>.
     */
    public final TableField<SimBuildRecord, BigDecimal> WEAPON_ATTACK_SPEED_BASE = createField(DSL.name("weapon_attack_speed_base"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_build.weapon_attack_speed_min</code>.
     */
    public final TableField<SimBuildRecord, BigDecimal> WEAPON_ATTACK_SPEED_MIN = createField(DSL.name("weapon_attack_speed_min"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_build.weapon_attack_speed_max</code>.
     */
    public final TableField<SimBuildRecord, BigDecimal> WEAPON_ATTACK_SPEED_MAX = createField(DSL.name("weapon_attack_speed_max"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_build.weapon_slot</code>.
     */
    public final TableField<SimBuildRecord, String> WEAPON_SLOT = createField(DSL.name("weapon_slot"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.sim_build.weapon_aliases</code>.
     */
    public final TableField<SimBuildRecord, JSONB> WEAPON_ALIASES = createField(DSL.name("weapon_aliases"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    private SimBuild(Name alias, Table<SimBuildRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SimBuild(Name alias, Table<SimBuildRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sim_build</code> table reference
     */
    public SimBuild(String alias) {
        this(DSL.name(alias), SIM_BUILD);
    }

    /**
     * Create an aliased <code>public.sim_build</code> table reference
     */
    public SimBuild(Name alias) {
        this(alias, SIM_BUILD);
    }

    /**
     * Create a <code>public.sim_build</code> table reference
     */
    public SimBuild() {
        this(DSL.name("sim_build"), null);
    }

    public <O extends Record> SimBuild(Table<O> path, ForeignKey<O, SimBuildRecord> childPath, InverseForeignKey<O, SimBuildRecord> parentPath) {
        super(path, childPath, parentPath, SIM_BUILD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimBuildPath extends SimBuild implements Path<SimBuildRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimBuildPath(Table<O> path, ForeignKey<O, SimBuildRecord> childPath, InverseForeignKey<O, SimBuildRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimBuildPath(Name alias, Table<SimBuildRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimBuildPath as(String alias) {
            return new SimBuildPath(DSL.name(alias), this);
        }

        @Override
        public SimBuildPath as(Name alias) {
            return new SimBuildPath(alias, this);
        }

        @Override
        public SimBuildPath as(Table<?> alias) {
            return new SimBuildPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SIM_BUILD_FINGERPRINT, Indexes.IDX_SIM_BUILD_RUN, Indexes.IDX_SIM_BUILD_RUN_FINGERPRINT, Indexes.IDX_SIM_BUILD_WEAPON_DAMAGE);
    }

    @Override
    public Identity<SimBuildRecord, Long> getIdentity() {
        return (Identity<SimBuildRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SimBuildRecord> getPrimaryKey() {
        return Keys.SIM_BUILD_PKEY;
    }

    @Override
    public List<ForeignKey<SimBuildRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SIM_BUILD__SIM_BUILD_RUN_ID_FKEY);
    }

    private transient SimRunPath _simRun;

    /**
     * Get the implicit join path to the <code>public.sim_run</code> table.
     */
    public SimRunPath simRun() {
        if (_simRun == null)
            _simRun = new SimRunPath(this, Keys.SIM_BUILD__SIM_BUILD_RUN_ID_FKEY, null);

        return _simRun;
    }

    private transient SimResultPath _simResult;

    /**
     * Get the implicit to-many join path to the <code>public.sim_result</code>
     * table
     */
    public SimResultPath simResult() {
        if (_simResult == null)
            _simResult = new SimResultPath(this, null, Keys.SIM_RESULT__SIM_RESULT_BUILD_ID_FKEY.getInverseKey());

        return _simResult;
    }

    private transient SimTracePath _simTrace;

    /**
     * Get the implicit to-many join path to the <code>public.sim_trace</code>
     * table
     */
    public SimTracePath simTrace() {
        if (_simTrace == null)
            _simTrace = new SimTracePath(this, null, Keys.SIM_TRACE__SIM_TRACE_BUILD_ID_FKEY.getInverseKey());

        return _simTrace;
    }

    @Override
    public SimBuild as(String alias) {
        return new SimBuild(DSL.name(alias), this);
    }

    @Override
    public SimBuild as(Name alias) {
        return new SimBuild(alias, this);
    }

    @Override
    public SimBuild as(Table<?> alias) {
        return new SimBuild(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimBuild rename(String name) {
        return new SimBuild(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimBuild rename(Name name) {
        return new SimBuild(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimBuild rename(Table<?> name) {
        return new SimBuild(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimBuild where(Condition condition) {
        return new SimBuild(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimBuild where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimBuild where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimBuild where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimBuild where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimBuild where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimBuild where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimBuild where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimBuild whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimBuild whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
