/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables;


import me.mykindos.betterpvp.balancesim.database.jooq.Indexes;
import me.mykindos.betterpvp.balancesim.database.jooq.Keys;
import me.mykindos.betterpvp.balancesim.database.jooq.Public;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild.SimBuildPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun.SimRunPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.records.SimDuelDiagnosticRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimDuelDiagnostic extends TableImpl<SimDuelDiagnosticRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sim_duel_diagnostic</code>
     */
    public static final SimDuelDiagnostic SIM_DUEL_DIAGNOSTIC = new SimDuelDiagnostic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimDuelDiagnosticRecord> getRecordType() {
        return SimDuelDiagnosticRecord.class;
    }

    /**
     * The column <code>public.sim_duel_diagnostic.id</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.run_id</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.build_id</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Long> BUILD_ID = createField(DSL.name("build_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.target_role</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, String> TARGET_ROLE = createField(DSL.name("target_role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.target_armor</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, String> TARGET_ARMOR = createField(DSL.name("target_armor"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.iteration</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> ITERATION = createField(DSL.name("iteration"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.arena_index</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> ARENA_INDEX = createField(DSL.name("arena_index"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_duels_fought</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> ATTACKER_DUELS_FOUGHT = createField(DSL.name("attacker_duels_fought"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_duels_fought</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> DEFENDER_DUELS_FOUGHT = createField(DSL.name("defender_duels_fought"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_revives</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> ATTACKER_REVIVES = createField(DSL.name("attacker_revives"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_revives</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> DEFENDER_REVIVES = createField(DSL.name("defender_revives"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_ever_died</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Boolean> ATTACKER_EVER_DIED = createField(DSL.name("attacker_ever_died"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_ever_died</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Boolean> DEFENDER_EVER_DIED = createField(DSL.name("defender_ever_died"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.outcome</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, String> OUTCOME = createField(DSL.name("outcome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.resolved_tick</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> RESOLVED_TICK = createField(DSL.name("resolved_tick"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.sim_duel_diagnostic.attacker_first_hit_tick</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> ATTACKER_FIRST_HIT_TICK = createField(DSL.name("attacker_first_hit_tick"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.sim_duel_diagnostic.defender_first_hit_tick</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> DEFENDER_FIRST_HIT_TICK = createField(DSL.name("defender_first_hit_tick"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_hits</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> ATTACKER_HITS = createField(DSL.name("attacker_hits"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_hits</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, Integer> DEFENDER_HITS = createField(DSL.name("defender_hits"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_damage</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> ATTACKER_DAMAGE = createField(DSL.name("attacker_damage"), SQLDataType.NUMERIC(10, 3).nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_damage</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> DEFENDER_DAMAGE = createField(DSL.name("defender_damage"), SQLDataType.NUMERIC(10, 3).nullable(false), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_start_health</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> ATTACKER_START_HEALTH = createField(DSL.name("attacker_start_health"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_max_health</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> ATTACKER_MAX_HEALTH = createField(DSL.name("attacker_max_health"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_start_health</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> DEFENDER_START_HEALTH = createField(DSL.name("defender_start_health"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_max_health</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> DEFENDER_MAX_HEALTH = createField(DSL.name("defender_max_health"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.attacker_end_health</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> ATTACKER_END_HEALTH = createField(DSL.name("attacker_end_health"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.defender_end_health</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, BigDecimal> DEFENDER_END_HEALTH = createField(DSL.name("defender_end_health"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_duel_diagnostic.detail</code>.
     */
    public final TableField<SimDuelDiagnosticRecord, JSONB> DETAIL = createField(DSL.name("detail"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    private SimDuelDiagnostic(Name alias, Table<SimDuelDiagnosticRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SimDuelDiagnostic(Name alias, Table<SimDuelDiagnosticRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sim_duel_diagnostic</code> table reference
     */
    public SimDuelDiagnostic(String alias) {
        this(DSL.name(alias), SIM_DUEL_DIAGNOSTIC);
    }

    /**
     * Create an aliased <code>public.sim_duel_diagnostic</code> table reference
     */
    public SimDuelDiagnostic(Name alias) {
        this(alias, SIM_DUEL_DIAGNOSTIC);
    }

    /**
     * Create a <code>public.sim_duel_diagnostic</code> table reference
     */
    public SimDuelDiagnostic() {
        this(DSL.name("sim_duel_diagnostic"), null);
    }

    public <O extends Record> SimDuelDiagnostic(Table<O> path, ForeignKey<O, SimDuelDiagnosticRecord> childPath, InverseForeignKey<O, SimDuelDiagnosticRecord> parentPath) {
        super(path, childPath, parentPath, SIM_DUEL_DIAGNOSTIC);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimDuelDiagnosticPath extends SimDuelDiagnostic implements Path<SimDuelDiagnosticRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimDuelDiagnosticPath(Table<O> path, ForeignKey<O, SimDuelDiagnosticRecord> childPath, InverseForeignKey<O, SimDuelDiagnosticRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimDuelDiagnosticPath(Name alias, Table<SimDuelDiagnosticRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimDuelDiagnosticPath as(String alias) {
            return new SimDuelDiagnosticPath(DSL.name(alias), this);
        }

        @Override
        public SimDuelDiagnosticPath as(Name alias) {
            return new SimDuelDiagnosticPath(alias, this);
        }

        @Override
        public SimDuelDiagnosticPath as(Table<?> alias) {
            return new SimDuelDiagnosticPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SIM_DUEL_DIAG_RUN_ARENA, Indexes.IDX_SIM_DUEL_DIAG_RUN_BUILD, Indexes.IDX_SIM_DUEL_DIAG_RUN_OUTCOME);
    }

    @Override
    public Identity<SimDuelDiagnosticRecord, Long> getIdentity() {
        return (Identity<SimDuelDiagnosticRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SimDuelDiagnosticRecord> getPrimaryKey() {
        return Keys.SIM_DUEL_DIAGNOSTIC_PKEY;
    }

    @Override
    public List<ForeignKey<SimDuelDiagnosticRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SIM_DUEL_DIAGNOSTIC__SIM_DUEL_DIAGNOSTIC_BUILD_ID_FKEY, Keys.SIM_DUEL_DIAGNOSTIC__SIM_DUEL_DIAGNOSTIC_RUN_ID_FKEY);
    }

    private transient SimBuildPath _simBuild;

    /**
     * Get the implicit join path to the <code>public.sim_build</code> table.
     */
    public SimBuildPath simBuild() {
        if (_simBuild == null)
            _simBuild = new SimBuildPath(this, Keys.SIM_DUEL_DIAGNOSTIC__SIM_DUEL_DIAGNOSTIC_BUILD_ID_FKEY, null);

        return _simBuild;
    }

    private transient SimRunPath _simRun;

    /**
     * Get the implicit join path to the <code>public.sim_run</code> table.
     */
    public SimRunPath simRun() {
        if (_simRun == null)
            _simRun = new SimRunPath(this, Keys.SIM_DUEL_DIAGNOSTIC__SIM_DUEL_DIAGNOSTIC_RUN_ID_FKEY, null);

        return _simRun;
    }

    @Override
    public SimDuelDiagnostic as(String alias) {
        return new SimDuelDiagnostic(DSL.name(alias), this);
    }

    @Override
    public SimDuelDiagnostic as(Name alias) {
        return new SimDuelDiagnostic(alias, this);
    }

    @Override
    public SimDuelDiagnostic as(Table<?> alias) {
        return new SimDuelDiagnostic(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimDuelDiagnostic rename(String name) {
        return new SimDuelDiagnostic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimDuelDiagnostic rename(Name name) {
        return new SimDuelDiagnostic(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimDuelDiagnostic rename(Table<?> name) {
        return new SimDuelDiagnostic(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDuelDiagnostic where(Condition condition) {
        return new SimDuelDiagnostic(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDuelDiagnostic where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDuelDiagnostic where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDuelDiagnostic where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDuelDiagnostic where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDuelDiagnostic where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDuelDiagnostic where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDuelDiagnostic where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDuelDiagnostic whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDuelDiagnostic whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
