/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables;


import me.mykindos.betterpvp.balancesim.database.jooq.Indexes;
import me.mykindos.betterpvp.balancesim.database.jooq.Keys;
import me.mykindos.betterpvp.balancesim.database.jooq.Public;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun.SimRunPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.records.SimDeltaPlanRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimDeltaPlan extends TableImpl<SimDeltaPlanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sim_delta_plan</code>
     */
    public static final SimDeltaPlan SIM_DELTA_PLAN = new SimDeltaPlan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimDeltaPlanRecord> getRecordType() {
        return SimDeltaPlanRecord.class;
    }

    /**
     * The column <code>public.sim_delta_plan.run_id</code>.
     */
    public final TableField<SimDeltaPlanRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_delta_plan.fingerprint</code>.
     */
    public final TableField<SimDeltaPlanRecord, String> FINGERPRINT = createField(DSL.name("fingerprint"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_delta_plan.target_role</code>.
     */
    public final TableField<SimDeltaPlanRecord, String> TARGET_ROLE = createField(DSL.name("target_role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_delta_plan.target_armor</code>.
     */
    public final TableField<SimDeltaPlanRecord, String> TARGET_ARMOR = createField(DSL.name("target_armor"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_delta_plan.config_scope_hash</code>.
     */
    public final TableField<SimDeltaPlanRecord, String> CONFIG_SCOPE_HASH = createField(DSL.name("config_scope_hash"), SQLDataType.CLOB.nullable(false), this, "");

    private SimDeltaPlan(Name alias, Table<SimDeltaPlanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SimDeltaPlan(Name alias, Table<SimDeltaPlanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sim_delta_plan</code> table reference
     */
    public SimDeltaPlan(String alias) {
        this(DSL.name(alias), SIM_DELTA_PLAN);
    }

    /**
     * Create an aliased <code>public.sim_delta_plan</code> table reference
     */
    public SimDeltaPlan(Name alias) {
        this(alias, SIM_DELTA_PLAN);
    }

    /**
     * Create a <code>public.sim_delta_plan</code> table reference
     */
    public SimDeltaPlan() {
        this(DSL.name("sim_delta_plan"), null);
    }

    public <O extends Record> SimDeltaPlan(Table<O> path, ForeignKey<O, SimDeltaPlanRecord> childPath, InverseForeignKey<O, SimDeltaPlanRecord> parentPath) {
        super(path, childPath, parentPath, SIM_DELTA_PLAN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimDeltaPlanPath extends SimDeltaPlan implements Path<SimDeltaPlanRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimDeltaPlanPath(Table<O> path, ForeignKey<O, SimDeltaPlanRecord> childPath, InverseForeignKey<O, SimDeltaPlanRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimDeltaPlanPath(Name alias, Table<SimDeltaPlanRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimDeltaPlanPath as(String alias) {
            return new SimDeltaPlanPath(DSL.name(alias), this);
        }

        @Override
        public SimDeltaPlanPath as(Name alias) {
            return new SimDeltaPlanPath(alias, this);
        }

        @Override
        public SimDeltaPlanPath as(Table<?> alias) {
            return new SimDeltaPlanPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SIM_DELTA_PLAN_RUN);
    }

    @Override
    public List<ForeignKey<SimDeltaPlanRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SIM_DELTA_PLAN__SIM_DELTA_PLAN_RUN_ID_FKEY);
    }

    private transient SimRunPath _simRun;

    /**
     * Get the implicit join path to the <code>public.sim_run</code> table.
     */
    public SimRunPath simRun() {
        if (_simRun == null)
            _simRun = new SimRunPath(this, Keys.SIM_DELTA_PLAN__SIM_DELTA_PLAN_RUN_ID_FKEY, null);

        return _simRun;
    }

    @Override
    public SimDeltaPlan as(String alias) {
        return new SimDeltaPlan(DSL.name(alias), this);
    }

    @Override
    public SimDeltaPlan as(Name alias) {
        return new SimDeltaPlan(alias, this);
    }

    @Override
    public SimDeltaPlan as(Table<?> alias) {
        return new SimDeltaPlan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimDeltaPlan rename(String name) {
        return new SimDeltaPlan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimDeltaPlan rename(Name name) {
        return new SimDeltaPlan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimDeltaPlan rename(Table<?> name) {
        return new SimDeltaPlan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDeltaPlan where(Condition condition) {
        return new SimDeltaPlan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDeltaPlan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDeltaPlan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDeltaPlan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDeltaPlan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDeltaPlan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDeltaPlan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimDeltaPlan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDeltaPlan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimDeltaPlan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
