/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables;


import me.mykindos.betterpvp.balancesim.database.jooq.Indexes;
import me.mykindos.betterpvp.balancesim.database.jooq.Keys;
import me.mykindos.betterpvp.balancesim.database.jooq.Public;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild.SimBuildPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimDeltaPlan.SimDeltaPlanPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimDuelDiagnostic.SimDuelDiagnosticPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimResult.SimResultPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimTrace.SimTracePath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.records.SimRunRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimRun extends TableImpl<SimRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sim_run</code>
     */
    public static final SimRun SIM_RUN = new SimRun();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimRunRecord> getRecordType() {
        return SimRunRecord.class;
    }

    /**
     * The column <code>public.sim_run.id</code>.
     */
    public final TableField<SimRunRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sim_run.realm</code>.
     */
    public final TableField<SimRunRecord, Integer> REALM = createField(DSL.name("realm"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_run.started_at</code>.
     */
    public final TableField<SimRunRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.sim_run.finished_at</code>.
     */
    public final TableField<SimRunRecord, OffsetDateTime> FINISHED_AT = createField(DSL.name("finished_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.sim_run.trigger</code>.
     */
    public final TableField<SimRunRecord, String> TRIGGER = createField(DSL.name("trigger"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_run.engine_version</code>.
     */
    public final TableField<SimRunRecord, String> ENGINE_VERSION = createField(DSL.name("engine_version"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_run.config_hash</code>.
     */
    public final TableField<SimRunRecord, String> CONFIG_HASH = createField(DSL.name("config_hash"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_run.scenario</code>.
     */
    public final TableField<SimRunRecord, JSONB> SCENARIO = createField(DSL.name("scenario"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.sim_run.status</code>.
     */
    public final TableField<SimRunRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'RUNNING'::text"), SQLDataType.CLOB)), this, "");

    private SimRun(Name alias, Table<SimRunRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SimRun(Name alias, Table<SimRunRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sim_run</code> table reference
     */
    public SimRun(String alias) {
        this(DSL.name(alias), SIM_RUN);
    }

    /**
     * Create an aliased <code>public.sim_run</code> table reference
     */
    public SimRun(Name alias) {
        this(alias, SIM_RUN);
    }

    /**
     * Create a <code>public.sim_run</code> table reference
     */
    public SimRun() {
        this(DSL.name("sim_run"), null);
    }

    public <O extends Record> SimRun(Table<O> path, ForeignKey<O, SimRunRecord> childPath, InverseForeignKey<O, SimRunRecord> parentPath) {
        super(path, childPath, parentPath, SIM_RUN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimRunPath extends SimRun implements Path<SimRunRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimRunPath(Table<O> path, ForeignKey<O, SimRunRecord> childPath, InverseForeignKey<O, SimRunRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimRunPath(Name alias, Table<SimRunRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimRunPath as(String alias) {
            return new SimRunPath(DSL.name(alias), this);
        }

        @Override
        public SimRunPath as(Name alias) {
            return new SimRunPath(alias, this);
        }

        @Override
        public SimRunPath as(Table<?> alias) {
            return new SimRunPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SIM_RUN_CONFIG_HASH, Indexes.IDX_SIM_RUN_REALM_STARTED);
    }

    @Override
    public Identity<SimRunRecord, Long> getIdentity() {
        return (Identity<SimRunRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SimRunRecord> getPrimaryKey() {
        return Keys.SIM_RUN_PKEY;
    }

    private transient SimBuildPath _simBuild;

    /**
     * Get the implicit to-many join path to the <code>public.sim_build</code>
     * table
     */
    public SimBuildPath simBuild() {
        if (_simBuild == null)
            _simBuild = new SimBuildPath(this, null, Keys.SIM_BUILD__SIM_BUILD_RUN_ID_FKEY.getInverseKey());

        return _simBuild;
    }

    private transient SimDeltaPlanPath _simDeltaPlan;

    /**
     * Get the implicit to-many join path to the
     * <code>public.sim_delta_plan</code> table
     */
    public SimDeltaPlanPath simDeltaPlan() {
        if (_simDeltaPlan == null)
            _simDeltaPlan = new SimDeltaPlanPath(this, null, Keys.SIM_DELTA_PLAN__SIM_DELTA_PLAN_RUN_ID_FKEY.getInverseKey());

        return _simDeltaPlan;
    }

    private transient SimDuelDiagnosticPath _simDuelDiagnostic;

    /**
     * Get the implicit to-many join path to the
     * <code>public.sim_duel_diagnostic</code> table
     */
    public SimDuelDiagnosticPath simDuelDiagnostic() {
        if (_simDuelDiagnostic == null)
            _simDuelDiagnostic = new SimDuelDiagnosticPath(this, null, Keys.SIM_DUEL_DIAGNOSTIC__SIM_DUEL_DIAGNOSTIC_RUN_ID_FKEY.getInverseKey());

        return _simDuelDiagnostic;
    }

    private transient SimResultPath _simResultMeasuredRunIdFkey;

    /**
     * Get the implicit to-many join path to the <code>public.sim_result</code>
     * table, via the <code>sim_result_measured_run_id_fkey</code> key
     */
    public SimResultPath simResultMeasuredRunIdFkey() {
        if (_simResultMeasuredRunIdFkey == null)
            _simResultMeasuredRunIdFkey = new SimResultPath(this, null, Keys.SIM_RESULT__SIM_RESULT_MEASURED_RUN_ID_FKEY.getInverseKey());

        return _simResultMeasuredRunIdFkey;
    }

    private transient SimResultPath _simResultRunIdFkey;

    /**
     * Get the implicit to-many join path to the <code>public.sim_result</code>
     * table, via the <code>sim_result_run_id_fkey</code> key
     */
    public SimResultPath simResultRunIdFkey() {
        if (_simResultRunIdFkey == null)
            _simResultRunIdFkey = new SimResultPath(this, null, Keys.SIM_RESULT__SIM_RESULT_RUN_ID_FKEY.getInverseKey());

        return _simResultRunIdFkey;
    }

    private transient SimTracePath _simTrace;

    /**
     * Get the implicit to-many join path to the <code>public.sim_trace</code>
     * table
     */
    public SimTracePath simTrace() {
        if (_simTrace == null)
            _simTrace = new SimTracePath(this, null, Keys.SIM_TRACE__SIM_TRACE_RUN_ID_FKEY.getInverseKey());

        return _simTrace;
    }

    @Override
    public SimRun as(String alias) {
        return new SimRun(DSL.name(alias), this);
    }

    @Override
    public SimRun as(Name alias) {
        return new SimRun(alias, this);
    }

    @Override
    public SimRun as(Table<?> alias) {
        return new SimRun(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimRun rename(String name) {
        return new SimRun(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimRun rename(Name name) {
        return new SimRun(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimRun rename(Table<?> name) {
        return new SimRun(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimRun where(Condition condition) {
        return new SimRun(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimRun where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimRun where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimRun where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimRun where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimRun where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimRun where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimRun where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimRun whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimRun whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
