/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables;


import me.mykindos.betterpvp.balancesim.database.jooq.Indexes;
import me.mykindos.betterpvp.balancesim.database.jooq.Keys;
import me.mykindos.betterpvp.balancesim.database.jooq.Public;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild.SimBuildPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun.SimRunPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.records.SimResultRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimResult extends TableImpl<SimResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sim_result</code>
     */
    public static final SimResult SIM_RESULT = new SimResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimResultRecord> getRecordType() {
        return SimResultRecord.class;
    }

    /**
     * The column <code>public.sim_result.id</code>.
     */
    public final TableField<SimResultRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sim_result.run_id</code>.
     */
    public final TableField<SimResultRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_result.build_id</code>.
     */
    public final TableField<SimResultRecord, Long> BUILD_ID = createField(DSL.name("build_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_result.target_role</code>.
     */
    public final TableField<SimResultRecord, String> TARGET_ROLE = createField(DSL.name("target_role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_result.target_armor</code>.
     */
    public final TableField<SimResultRecord, String> TARGET_ARMOR = createField(DSL.name("target_armor"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_result.target_hp</code>.
     */
    public final TableField<SimResultRecord, BigDecimal> TARGET_HP = createField(DSL.name("target_hp"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "");

    /**
     * The column <code>public.sim_result.target_skills</code>.
     */
    public final TableField<SimResultRecord, JSONB> TARGET_SKILLS = createField(DSL.name("target_skills"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.sim_result.target_points</code>.
     */
    public final TableField<SimResultRecord, Integer> TARGET_POINTS = createField(DSL.name("target_points"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.sim_result.dmg_per_hit</code>.
     */
    public final TableField<SimResultRecord, BigDecimal> DMG_PER_HIT = createField(DSL.name("dmg_per_hit"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_result.dps_sustained</code>.
     */
    public final TableField<SimResultRecord, BigDecimal> DPS_SUSTAINED = createField(DSL.name("dps_sustained"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_result.dps_burst</code>.
     */
    public final TableField<SimResultRecord, BigDecimal> DPS_BURST = createField(DSL.name("dps_burst"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_result.ttk_s</code>.
     */
    public final TableField<SimResultRecord, BigDecimal> TTK_S = createField(DSL.name("ttk_s"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_result.hits_to_kill</code>.
     */
    public final TableField<SimResultRecord, BigDecimal> HITS_TO_KILL = createField(DSL.name("hits_to_kill"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_result.energy_limited</code>.
     */
    public final TableField<SimResultRecord, Boolean> ENERGY_LIMITED = createField(DSL.name("energy_limited"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.sim_result.extras</code>.
     */
    public final TableField<SimResultRecord, JSONB> EXTRAS = createField(DSL.name("extras"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    private SimResult(Name alias, Table<SimResultRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SimResult(Name alias, Table<SimResultRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sim_result</code> table reference
     */
    public SimResult(String alias) {
        this(DSL.name(alias), SIM_RESULT);
    }

    /**
     * Create an aliased <code>public.sim_result</code> table reference
     */
    public SimResult(Name alias) {
        this(alias, SIM_RESULT);
    }

    /**
     * Create a <code>public.sim_result</code> table reference
     */
    public SimResult() {
        this(DSL.name("sim_result"), null);
    }

    public <O extends Record> SimResult(Table<O> path, ForeignKey<O, SimResultRecord> childPath, InverseForeignKey<O, SimResultRecord> parentPath) {
        super(path, childPath, parentPath, SIM_RESULT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimResultPath extends SimResult implements Path<SimResultRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimResultPath(Table<O> path, ForeignKey<O, SimResultRecord> childPath, InverseForeignKey<O, SimResultRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimResultPath(Name alias, Table<SimResultRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimResultPath as(String alias) {
            return new SimResultPath(DSL.name(alias), this);
        }

        @Override
        public SimResultPath as(Name alias) {
            return new SimResultPath(alias, this);
        }

        @Override
        public SimResultPath as(Table<?> alias) {
            return new SimResultPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SIM_RESULT_BUILD, Indexes.IDX_SIM_RESULT_RUN);
    }

    @Override
    public Identity<SimResultRecord, Long> getIdentity() {
        return (Identity<SimResultRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SimResultRecord> getPrimaryKey() {
        return Keys.SIM_RESULT_PKEY;
    }

    @Override
    public List<ForeignKey<SimResultRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SIM_RESULT__SIM_RESULT_BUILD_ID_FKEY, Keys.SIM_RESULT__SIM_RESULT_RUN_ID_FKEY);
    }

    private transient SimBuildPath _simBuild;

    /**
     * Get the implicit join path to the <code>public.sim_build</code> table.
     */
    public SimBuildPath simBuild() {
        if (_simBuild == null)
            _simBuild = new SimBuildPath(this, Keys.SIM_RESULT__SIM_RESULT_BUILD_ID_FKEY, null);

        return _simBuild;
    }

    private transient SimRunPath _simRun;

    /**
     * Get the implicit join path to the <code>public.sim_run</code> table.
     */
    public SimRunPath simRun() {
        if (_simRun == null)
            _simRun = new SimRunPath(this, Keys.SIM_RESULT__SIM_RESULT_RUN_ID_FKEY, null);

        return _simRun;
    }

    @Override
    public SimResult as(String alias) {
        return new SimResult(DSL.name(alias), this);
    }

    @Override
    public SimResult as(Name alias) {
        return new SimResult(alias, this);
    }

    @Override
    public SimResult as(Table<?> alias) {
        return new SimResult(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimResult rename(String name) {
        return new SimResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimResult rename(Name name) {
        return new SimResult(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimResult rename(Table<?> name) {
        return new SimResult(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimResult where(Condition condition) {
        return new SimResult(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimResult where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimResult where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimResult where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimResult where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimResult where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimResult where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimResult where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimResult whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimResult whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
