/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables;


import me.mykindos.betterpvp.balancesim.database.jooq.Indexes;
import me.mykindos.betterpvp.balancesim.database.jooq.Keys;
import me.mykindos.betterpvp.balancesim.database.jooq.Public;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild.SimBuildPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun.SimRunPath;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.records.SimTraceRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimTrace extends TableImpl<SimTraceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sim_trace</code>
     */
    public static final SimTrace SIM_TRACE = new SimTrace();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimTraceRecord> getRecordType() {
        return SimTraceRecord.class;
    }

    /**
     * The column <code>public.sim_trace.id</code>.
     */
    public final TableField<SimTraceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sim_trace.run_id</code>.
     */
    public final TableField<SimTraceRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.build_id</code>.
     */
    public final TableField<SimTraceRecord, Long> BUILD_ID = createField(DSL.name("build_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.t_ms</code>.
     */
    public final TableField<SimTraceRecord, Long> T_MS = createField(DSL.name("t_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.event</code>.
     */
    public final TableField<SimTraceRecord, String> EVENT = createField(DSL.name("event"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.amount</code>.
     */
    public final TableField<SimTraceRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(10, 3), this, "");

    /**
     * The column <code>public.sim_trace.target_role</code>.
     */
    public final TableField<SimTraceRecord, String> TARGET_ROLE = createField(DSL.name("target_role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.target_armor</code>.
     */
    public final TableField<SimTraceRecord, String> TARGET_ARMOR = createField(DSL.name("target_armor"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.iteration</code>.
     */
    public final TableField<SimTraceRecord, Integer> ITERATION = createField(DSL.name("iteration"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.arena_index</code>.
     */
    public final TableField<SimTraceRecord, Integer> ARENA_INDEX = createField(DSL.name("arena_index"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.tick</code>.
     */
    public final TableField<SimTraceRecord, Integer> TICK = createField(DSL.name("tick"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.seq</code>.
     */
    public final TableField<SimTraceRecord, Integer> SEQ = createField(DSL.name("seq"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.actor</code>.
     */
    public final TableField<SimTraceRecord, String> ACTOR = createField(DSL.name("actor"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sim_trace.raw_amount</code>.
     */
    public final TableField<SimTraceRecord, BigDecimal> RAW_AMOUNT = createField(DSL.name("raw_amount"), SQLDataType.NUMERIC(10, 3), this, "");

    private SimTrace(Name alias, Table<SimTraceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SimTrace(Name alias, Table<SimTraceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sim_trace</code> table reference
     */
    public SimTrace(String alias) {
        this(DSL.name(alias), SIM_TRACE);
    }

    /**
     * Create an aliased <code>public.sim_trace</code> table reference
     */
    public SimTrace(Name alias) {
        this(alias, SIM_TRACE);
    }

    /**
     * Create a <code>public.sim_trace</code> table reference
     */
    public SimTrace() {
        this(DSL.name("sim_trace"), null);
    }

    public <O extends Record> SimTrace(Table<O> path, ForeignKey<O, SimTraceRecord> childPath, InverseForeignKey<O, SimTraceRecord> parentPath) {
        super(path, childPath, parentPath, SIM_TRACE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimTracePath extends SimTrace implements Path<SimTraceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimTracePath(Table<O> path, ForeignKey<O, SimTraceRecord> childPath, InverseForeignKey<O, SimTraceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimTracePath(Name alias, Table<SimTraceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimTracePath as(String alias) {
            return new SimTracePath(DSL.name(alias), this);
        }

        @Override
        public SimTracePath as(Name alias) {
            return new SimTracePath(alias, this);
        }

        @Override
        public SimTracePath as(Table<?> alias) {
            return new SimTracePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SIM_TRACE_DUEL, Indexes.IDX_SIM_TRACE_RUN_BUILD);
    }

    @Override
    public Identity<SimTraceRecord, Long> getIdentity() {
        return (Identity<SimTraceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SimTraceRecord> getPrimaryKey() {
        return Keys.SIM_TRACE_PKEY;
    }

    @Override
    public List<ForeignKey<SimTraceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SIM_TRACE__SIM_TRACE_BUILD_ID_FKEY, Keys.SIM_TRACE__SIM_TRACE_RUN_ID_FKEY);
    }

    private transient SimBuildPath _simBuild;

    /**
     * Get the implicit join path to the <code>public.sim_build</code> table.
     */
    public SimBuildPath simBuild() {
        if (_simBuild == null)
            _simBuild = new SimBuildPath(this, Keys.SIM_TRACE__SIM_TRACE_BUILD_ID_FKEY, null);

        return _simBuild;
    }

    private transient SimRunPath _simRun;

    /**
     * Get the implicit join path to the <code>public.sim_run</code> table.
     */
    public SimRunPath simRun() {
        if (_simRun == null)
            _simRun = new SimRunPath(this, Keys.SIM_TRACE__SIM_TRACE_RUN_ID_FKEY, null);

        return _simRun;
    }

    @Override
    public SimTrace as(String alias) {
        return new SimTrace(DSL.name(alias), this);
    }

    @Override
    public SimTrace as(Name alias) {
        return new SimTrace(alias, this);
    }

    @Override
    public SimTrace as(Table<?> alias) {
        return new SimTrace(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimTrace rename(String name) {
        return new SimTrace(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimTrace rename(Name name) {
        return new SimTrace(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimTrace rename(Table<?> name) {
        return new SimTrace(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimTrace where(Condition condition) {
        return new SimTrace(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimTrace where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimTrace where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimTrace where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimTrace where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimTrace where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimTrace where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SimTrace where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimTrace whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SimTrace whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
