/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Content.ContentPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ContentLinksRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContentLinks extends TableImpl<ContentLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.content_links</code>
     */
    public static final ContentLinks CONTENT_LINKS = new ContentLinks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContentLinksRecord> getRecordType() {
        return ContentLinksRecord.class;
    }

    /**
     * The column <code>public.content_links.from_content_id</code>.
     */
    public final TableField<ContentLinksRecord, UUID> FROM_CONTENT_ID = createField(DSL.name("from_content_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.content_links.to_content_id</code>.
     */
    public final TableField<ContentLinksRecord, UUID> TO_CONTENT_ID = createField(DSL.name("to_content_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.content_links.kind</code>.
     */
    public final TableField<ContentLinksRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.CLOB.nullable(false), this, "");

    private ContentLinks(Name alias, Table<ContentLinksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ContentLinks(Name alias, Table<ContentLinksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.content_links</code> table reference
     */
    public ContentLinks(String alias) {
        this(DSL.name(alias), CONTENT_LINKS);
    }

    /**
     * Create an aliased <code>public.content_links</code> table reference
     */
    public ContentLinks(Name alias) {
        this(alias, CONTENT_LINKS);
    }

    /**
     * Create a <code>public.content_links</code> table reference
     */
    public ContentLinks() {
        this(DSL.name("content_links"), null);
    }

    public <O extends Record> ContentLinks(Table<O> path, ForeignKey<O, ContentLinksRecord> childPath, InverseForeignKey<O, ContentLinksRecord> parentPath) {
        super(path, childPath, parentPath, CONTENT_LINKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContentLinksPath extends ContentLinks implements Path<ContentLinksRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ContentLinksPath(Table<O> path, ForeignKey<O, ContentLinksRecord> childPath, InverseForeignKey<O, ContentLinksRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContentLinksPath(Name alias, Table<ContentLinksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContentLinksPath as(String alias) {
            return new ContentLinksPath(DSL.name(alias), this);
        }

        @Override
        public ContentLinksPath as(Name alias) {
            return new ContentLinksPath(alias, this);
        }

        @Override
        public ContentLinksPath as(Table<?> alias) {
            return new ContentLinksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ContentLinksRecord> getPrimaryKey() {
        return Keys.CONTENT_LINKS_PKEY;
    }

    @Override
    public List<ForeignKey<ContentLinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONTENT_LINKS__CONTENT_LINKS_FROM_CONTENT_ID_FKEY);
    }

    private transient ContentPath _content;

    /**
     * Get the implicit join path to the <code>public.content</code> table.
     */
    public ContentPath content() {
        if (_content == null)
            _content = new ContentPath(this, Keys.CONTENT_LINKS__CONTENT_LINKS_FROM_CONTENT_ID_FKEY, null);

        return _content;
    }

    @Override
    public ContentLinks as(String alias) {
        return new ContentLinks(DSL.name(alias), this);
    }

    @Override
    public ContentLinks as(Name alias) {
        return new ContentLinks(alias, this);
    }

    @Override
    public ContentLinks as(Table<?> alias) {
        return new ContentLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentLinks rename(String name) {
        return new ContentLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentLinks rename(Name name) {
        return new ContentLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentLinks rename(Table<?> name) {
        return new ContentLinks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentLinks where(Condition condition) {
        return new ContentLinks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentLinks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentLinks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentLinks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentLinks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentLinks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentLinks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentLinks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentLinks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentLinks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
