/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.ContentLinks.ContentLinksPath;
import me.mykindos.betterpvp.core.database.jooq.tables.ContentSnapshots.ContentSnapshotsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ContentRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Content extends TableImpl<ContentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.content</code>
     */
    public static final Content CONTENT = new Content();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContentRecord> getRecordType() {
        return ContentRecord.class;
    }

    /**
     * The column <code>public.content.id</code>.
     */
    public final TableField<ContentRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.content.type</code>.
     */
    public final TableField<ContentRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.content.name</code>.
     */
    public final TableField<ContentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.content.description</code>.
     */
    public final TableField<ContentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.content.status</code>.
     */
    public final TableField<ContentRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'draft'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.content.draft</code>.
     */
    public final TableField<ContentRecord, JSONB> DRAFT = createField(DSL.name("draft"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.content.published</code>.
     */
    public final TableField<ContentRecord, JSONB> PUBLISHED = createField(DSL.name("published"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.content.version</code>.
     */
    public final TableField<ContentRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.content.revision</code>.
     */
    public final TableField<ContentRecord, Integer> REVISION = createField(DSL.name("revision"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.content.created_at</code>.
     */
    public final TableField<ContentRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.content.created_by</code>.
     */
    public final TableField<ContentRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.content.updated_at</code>.
     */
    public final TableField<ContentRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.content.updated_by</code>.
     */
    public final TableField<ContentRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.content.published_at</code>.
     */
    public final TableField<ContentRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.content.published_by</code>.
     */
    public final TableField<ContentRecord, UUID> PUBLISHED_BY = createField(DSL.name("published_by"), SQLDataType.UUID, this, "");

    private Content(Name alias, Table<ContentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Content(Name alias, Table<ContentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.content</code> table reference
     */
    public Content(String alias) {
        this(DSL.name(alias), CONTENT);
    }

    /**
     * Create an aliased <code>public.content</code> table reference
     */
    public Content(Name alias) {
        this(alias, CONTENT);
    }

    /**
     * Create a <code>public.content</code> table reference
     */
    public Content() {
        this(DSL.name("content"), null);
    }

    public <O extends Record> Content(Table<O> path, ForeignKey<O, ContentRecord> childPath, InverseForeignKey<O, ContentRecord> parentPath) {
        super(path, childPath, parentPath, CONTENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContentPath extends Content implements Path<ContentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ContentPath(Table<O> path, ForeignKey<O, ContentRecord> childPath, InverseForeignKey<O, ContentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContentPath(Name alias, Table<ContentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContentPath as(String alias) {
            return new ContentPath(DSL.name(alias), this);
        }

        @Override
        public ContentPath as(Name alias) {
            return new ContentPath(alias, this);
        }

        @Override
        public ContentPath as(Table<?> alias) {
            return new ContentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CONTENT_TYPE_STATUS_IDX);
    }

    @Override
    public UniqueKey<ContentRecord> getPrimaryKey() {
        return Keys.CONTENT_PKEY;
    }

    private transient ContentLinksPath _contentLinks;

    /**
     * Get the implicit to-many join path to the
     * <code>public.content_links</code> table
     */
    public ContentLinksPath contentLinks() {
        if (_contentLinks == null)
            _contentLinks = new ContentLinksPath(this, null, Keys.CONTENT_LINKS__CONTENT_LINKS_FROM_CONTENT_ID_FKEY.getInverseKey());

        return _contentLinks;
    }

    private transient ContentSnapshotsPath _contentSnapshots;

    /**
     * Get the implicit to-many join path to the
     * <code>public.content_snapshots</code> table
     */
    public ContentSnapshotsPath contentSnapshots() {
        if (_contentSnapshots == null)
            _contentSnapshots = new ContentSnapshotsPath(this, null, Keys.CONTENT_SNAPSHOTS__CONTENT_SNAPSHOTS_CONTENT_ID_FKEY.getInverseKey());

        return _contentSnapshots;
    }

    @Override
    public Content as(String alias) {
        return new Content(DSL.name(alias), this);
    }

    @Override
    public Content as(Name alias) {
        return new Content(alias, this);
    }

    @Override
    public Content as(Table<?> alias) {
        return new Content(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Content rename(String name) {
        return new Content(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Content rename(Name name) {
        return new Content(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Content rename(Table<?> name) {
        return new Content(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Content where(Condition condition) {
        return new Content(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Content where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Content where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Content where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Content where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Content where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Content where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Content where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Content whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Content whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
