/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Content.ContentPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ContentSnapshotsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContentSnapshots extends TableImpl<ContentSnapshotsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.content_snapshots</code>
     */
    public static final ContentSnapshots CONTENT_SNAPSHOTS = new ContentSnapshots();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContentSnapshotsRecord> getRecordType() {
        return ContentSnapshotsRecord.class;
    }

    /**
     * The column <code>public.content_snapshots.id</code>.
     */
    public final TableField<ContentSnapshotsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.content_snapshots.content_id</code>.
     */
    public final TableField<ContentSnapshotsRecord, UUID> CONTENT_ID = createField(DSL.name("content_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.content_snapshots.version</code>.
     */
    public final TableField<ContentSnapshotsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.content_snapshots.payload</code>.
     */
    public final TableField<ContentSnapshotsRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.content_snapshots.label</code>.
     */
    public final TableField<ContentSnapshotsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.content_snapshots.created_at</code>.
     */
    public final TableField<ContentSnapshotsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.content_snapshots.created_by</code>.
     */
    public final TableField<ContentSnapshotsRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    private ContentSnapshots(Name alias, Table<ContentSnapshotsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ContentSnapshots(Name alias, Table<ContentSnapshotsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.content_snapshots</code> table reference
     */
    public ContentSnapshots(String alias) {
        this(DSL.name(alias), CONTENT_SNAPSHOTS);
    }

    /**
     * Create an aliased <code>public.content_snapshots</code> table reference
     */
    public ContentSnapshots(Name alias) {
        this(alias, CONTENT_SNAPSHOTS);
    }

    /**
     * Create a <code>public.content_snapshots</code> table reference
     */
    public ContentSnapshots() {
        this(DSL.name("content_snapshots"), null);
    }

    public <O extends Record> ContentSnapshots(Table<O> path, ForeignKey<O, ContentSnapshotsRecord> childPath, InverseForeignKey<O, ContentSnapshotsRecord> parentPath) {
        super(path, childPath, parentPath, CONTENT_SNAPSHOTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContentSnapshotsPath extends ContentSnapshots implements Path<ContentSnapshotsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ContentSnapshotsPath(Table<O> path, ForeignKey<O, ContentSnapshotsRecord> childPath, InverseForeignKey<O, ContentSnapshotsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContentSnapshotsPath(Name alias, Table<ContentSnapshotsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContentSnapshotsPath as(String alias) {
            return new ContentSnapshotsPath(DSL.name(alias), this);
        }

        @Override
        public ContentSnapshotsPath as(Name alias) {
            return new ContentSnapshotsPath(alias, this);
        }

        @Override
        public ContentSnapshotsPath as(Table<?> alias) {
            return new ContentSnapshotsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ContentSnapshotsRecord> getPrimaryKey() {
        return Keys.CONTENT_SNAPSHOTS_PKEY;
    }

    @Override
    public List<ForeignKey<ContentSnapshotsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONTENT_SNAPSHOTS__CONTENT_SNAPSHOTS_CONTENT_ID_FKEY);
    }

    private transient ContentPath _content;

    /**
     * Get the implicit join path to the <code>public.content</code> table.
     */
    public ContentPath content() {
        if (_content == null)
            _content = new ContentPath(this, Keys.CONTENT_SNAPSHOTS__CONTENT_SNAPSHOTS_CONTENT_ID_FKEY, null);

        return _content;
    }

    @Override
    public ContentSnapshots as(String alias) {
        return new ContentSnapshots(DSL.name(alias), this);
    }

    @Override
    public ContentSnapshots as(Name alias) {
        return new ContentSnapshots(alias, this);
    }

    @Override
    public ContentSnapshots as(Table<?> alias) {
        return new ContentSnapshots(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentSnapshots rename(String name) {
        return new ContentSnapshots(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentSnapshots rename(Name name) {
        return new ContentSnapshots(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentSnapshots rename(Table<?> name) {
        return new ContentSnapshots(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentSnapshots where(Condition condition) {
        return new ContentSnapshots(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentSnapshots where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentSnapshots where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentSnapshots where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentSnapshots where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentSnapshots where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentSnapshots where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentSnapshots where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentSnapshots whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentSnapshots whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
