/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GameNpcFactoriesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameNpcFactories extends TableImpl<GameNpcFactoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_npc_factories</code>
     */
    public static final GameNpcFactories GAME_NPC_FACTORIES = new GameNpcFactories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameNpcFactoriesRecord> getRecordType() {
        return GameNpcFactoriesRecord.class;
    }

    /**
     * The column <code>public.game_npc_factories.factory</code>.
     */
    public final TableField<GameNpcFactoriesRecord, String> FACTORY = createField(DSL.name("factory"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_npc_factories.type</code>.
     */
    public final TableField<GameNpcFactoriesRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    private GameNpcFactories(Name alias, Table<GameNpcFactoriesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameNpcFactories(Name alias, Table<GameNpcFactoriesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_npc_factories</code> table reference
     */
    public GameNpcFactories(String alias) {
        this(DSL.name(alias), GAME_NPC_FACTORIES);
    }

    /**
     * Create an aliased <code>public.game_npc_factories</code> table reference
     */
    public GameNpcFactories(Name alias) {
        this(alias, GAME_NPC_FACTORIES);
    }

    /**
     * Create a <code>public.game_npc_factories</code> table reference
     */
    public GameNpcFactories() {
        this(DSL.name("game_npc_factories"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GameNpcFactoriesRecord> getPrimaryKey() {
        return Keys.GAME_NPC_FACTORIES_PKEY;
    }

    @Override
    public GameNpcFactories as(String alias) {
        return new GameNpcFactories(DSL.name(alias), this);
    }

    @Override
    public GameNpcFactories as(Name alias) {
        return new GameNpcFactories(alias, this);
    }

    @Override
    public GameNpcFactories as(Table<?> alias) {
        return new GameNpcFactories(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameNpcFactories rename(String name) {
        return new GameNpcFactories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameNpcFactories rename(Name name) {
        return new GameNpcFactories(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameNpcFactories rename(Table<?> name) {
        return new GameNpcFactories(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNpcFactories where(Condition condition) {
        return new GameNpcFactories(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNpcFactories where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNpcFactories where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNpcFactories where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNpcFactories where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNpcFactories where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNpcFactories where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNpcFactories where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNpcFactories whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNpcFactories whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
