/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GameItemsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameItems extends TableImpl<GameItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_items</code>
     */
    public static final GameItems GAME_ITEMS = new GameItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameItemsRecord> getRecordType() {
        return GameItemsRecord.class;
    }

    /**
     * The column <code>public.game_items.key</code>.
     */
    public final TableField<GameItemsRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_items.display_name</code>.
     */
    public final TableField<GameItemsRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_items.source</code>.
     */
    public final TableField<GameItemsRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'vanilla'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.game_items.material</code>.
     */
    public final TableField<GameItemsRecord, String> MATERIAL = createField(DSL.name("material"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.game_items.tags</code>.
     */
    public final TableField<GameItemsRecord, String[]> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::text[]"), SQLDataType.CLOB)).array(), this, "");

    /**
     * The column <code>public.game_items.updated_at</code>.
     */
    public final TableField<GameItemsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private GameItems(Name alias, Table<GameItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameItems(Name alias, Table<GameItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_items</code> table reference
     */
    public GameItems(String alias) {
        this(DSL.name(alias), GAME_ITEMS);
    }

    /**
     * Create an aliased <code>public.game_items</code> table reference
     */
    public GameItems(Name alias) {
        this(alias, GAME_ITEMS);
    }

    /**
     * Create a <code>public.game_items</code> table reference
     */
    public GameItems() {
        this(DSL.name("game_items"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GameItemsRecord> getPrimaryKey() {
        return Keys.GAME_ITEMS_PKEY;
    }

    @Override
    public GameItems as(String alias) {
        return new GameItems(DSL.name(alias), this);
    }

    @Override
    public GameItems as(Name alias) {
        return new GameItems(alias, this);
    }

    @Override
    public GameItems as(Table<?> alias) {
        return new GameItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameItems rename(String name) {
        return new GameItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameItems rename(Name name) {
        return new GameItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameItems rename(Table<?> name) {
        return new GameItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameItems where(Condition condition) {
        return new GameItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
