/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GameProfessionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameProfessions extends TableImpl<GameProfessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_professions</code>
     */
    public static final GameProfessions GAME_PROFESSIONS = new GameProfessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameProfessionsRecord> getRecordType() {
        return GameProfessionsRecord.class;
    }

    /**
     * The column <code>public.game_professions.key</code>.
     */
    public final TableField<GameProfessionsRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_professions.display_name</code>.
     */
    public final TableField<GameProfessionsRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_professions.max_level</code>.
     */
    public final TableField<GameProfessionsRecord, Integer> MAX_LEVEL = createField(DSL.name("max_level"), SQLDataType.INTEGER, this, "");

    private GameProfessions(Name alias, Table<GameProfessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameProfessions(Name alias, Table<GameProfessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_professions</code> table reference
     */
    public GameProfessions(String alias) {
        this(DSL.name(alias), GAME_PROFESSIONS);
    }

    /**
     * Create an aliased <code>public.game_professions</code> table reference
     */
    public GameProfessions(Name alias) {
        this(alias, GAME_PROFESSIONS);
    }

    /**
     * Create a <code>public.game_professions</code> table reference
     */
    public GameProfessions() {
        this(DSL.name("game_professions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GameProfessionsRecord> getPrimaryKey() {
        return Keys.GAME_PROFESSIONS_PKEY;
    }

    @Override
    public GameProfessions as(String alias) {
        return new GameProfessions(DSL.name(alias), this);
    }

    @Override
    public GameProfessions as(Name alias) {
        return new GameProfessions(alias, this);
    }

    @Override
    public GameProfessions as(Table<?> alias) {
        return new GameProfessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameProfessions rename(String name) {
        return new GameProfessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameProfessions rename(Name name) {
        return new GameProfessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameProfessions rename(Table<?> name) {
        return new GameProfessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameProfessions where(Condition condition) {
        return new GameProfessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameProfessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameProfessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameProfessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameProfessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameProfessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameProfessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameProfessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameProfessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameProfessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
