/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GameZonesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameZones extends TableImpl<GameZonesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_zones</code>
     */
    public static final GameZones GAME_ZONES = new GameZones();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameZonesRecord> getRecordType() {
        return GameZonesRecord.class;
    }

    /**
     * The column <code>public.game_zones.key</code>.
     */
    public final TableField<GameZonesRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_zones.display_name</code>.
     */
    public final TableField<GameZonesRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.game_zones.world</code>.
     */
    public final TableField<GameZonesRecord, String> WORLD = createField(DSL.name("world"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.game_zones.tags</code>.
     */
    public final TableField<GameZonesRecord, String[]> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::text[]"), SQLDataType.CLOB)).array(), this, "");

    private GameZones(Name alias, Table<GameZonesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameZones(Name alias, Table<GameZonesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_zones</code> table reference
     */
    public GameZones(String alias) {
        this(DSL.name(alias), GAME_ZONES);
    }

    /**
     * Create an aliased <code>public.game_zones</code> table reference
     */
    public GameZones(Name alias) {
        this(alias, GAME_ZONES);
    }

    /**
     * Create a <code>public.game_zones</code> table reference
     */
    public GameZones() {
        this(DSL.name("game_zones"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GameZonesRecord> getPrimaryKey() {
        return Keys.GAME_ZONES_PKEY;
    }

    @Override
    public GameZones as(String alias) {
        return new GameZones(DSL.name(alias), this);
    }

    @Override
    public GameZones as(Name alias) {
        return new GameZones(alias, this);
    }

    @Override
    public GameZones as(Table<?> alias) {
        return new GameZones(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameZones rename(String name) {
        return new GameZones(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameZones rename(Name name) {
        return new GameZones(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameZones rename(Table<?> name) {
        return new GameZones(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameZones where(Condition condition) {
        return new GameZones(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameZones where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameZones where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameZones where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameZones where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameZones where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameZones where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameZones where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameZones whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameZones whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
