/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.PurityDistributionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurityDistributions extends TableImpl<PurityDistributionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purity_distributions</code>
     */
    public static final PurityDistributions PURITY_DISTRIBUTIONS = new PurityDistributions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurityDistributionsRecord> getRecordType() {
        return PurityDistributionsRecord.class;
    }

    /**
     * The column <code>public.purity_distributions.name</code>.
     */
    public final TableField<PurityDistributionsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.purity_distributions.draft</code>.
     */
    public final TableField<PurityDistributionsRecord, JSONB> DRAFT = createField(DSL.name("draft"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.purity_distributions.published</code>.
     */
    public final TableField<PurityDistributionsRecord, JSONB> PUBLISHED = createField(DSL.name("published"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.purity_distributions.updated_at</code>.
     */
    public final TableField<PurityDistributionsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.purity_distributions.published_at</code>.
     */
    public final TableField<PurityDistributionsRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PurityDistributions(Name alias, Table<PurityDistributionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurityDistributions(Name alias, Table<PurityDistributionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purity_distributions</code> table
     * reference
     */
    public PurityDistributions(String alias) {
        this(DSL.name(alias), PURITY_DISTRIBUTIONS);
    }

    /**
     * Create an aliased <code>public.purity_distributions</code> table
     * reference
     */
    public PurityDistributions(Name alias) {
        this(alias, PURITY_DISTRIBUTIONS);
    }

    /**
     * Create a <code>public.purity_distributions</code> table reference
     */
    public PurityDistributions() {
        this(DSL.name("purity_distributions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PurityDistributionsRecord> getPrimaryKey() {
        return Keys.PURITY_DISTRIBUTIONS_PKEY;
    }

    @Override
    public PurityDistributions as(String alias) {
        return new PurityDistributions(DSL.name(alias), this);
    }

    @Override
    public PurityDistributions as(Name alias) {
        return new PurityDistributions(alias, this);
    }

    @Override
    public PurityDistributions as(Table<?> alias) {
        return new PurityDistributions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityDistributions rename(String name) {
        return new PurityDistributions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityDistributions rename(Name name) {
        return new PurityDistributions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityDistributions rename(Table<?> name) {
        return new PurityDistributions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityDistributions where(Condition condition) {
        return new PurityDistributions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityDistributions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityDistributions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityDistributions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityDistributions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityDistributions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityDistributions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityDistributions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityDistributions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityDistributions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
