/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.PurityReforgeBiasRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurityReforgeBias extends TableImpl<PurityReforgeBiasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purity_reforge_bias</code>
     */
    public static final PurityReforgeBias PURITY_REFORGE_BIAS = new PurityReforgeBias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurityReforgeBiasRecord> getRecordType() {
        return PurityReforgeBiasRecord.class;
    }

    /**
     * The column <code>public.purity_reforge_bias.purity</code>.
     */
    public final TableField<PurityReforgeBiasRecord, String> PURITY = createField(DSL.name("purity"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.purity_reforge_bias.draft</code>.
     */
    public final TableField<PurityReforgeBiasRecord, JSONB> DRAFT = createField(DSL.name("draft"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.purity_reforge_bias.published</code>.
     */
    public final TableField<PurityReforgeBiasRecord, JSONB> PUBLISHED = createField(DSL.name("published"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.purity_reforge_bias.updated_at</code>.
     */
    public final TableField<PurityReforgeBiasRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.purity_reforge_bias.published_at</code>.
     */
    public final TableField<PurityReforgeBiasRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PurityReforgeBias(Name alias, Table<PurityReforgeBiasRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurityReforgeBias(Name alias, Table<PurityReforgeBiasRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purity_reforge_bias</code> table reference
     */
    public PurityReforgeBias(String alias) {
        this(DSL.name(alias), PURITY_REFORGE_BIAS);
    }

    /**
     * Create an aliased <code>public.purity_reforge_bias</code> table reference
     */
    public PurityReforgeBias(Name alias) {
        this(alias, PURITY_REFORGE_BIAS);
    }

    /**
     * Create a <code>public.purity_reforge_bias</code> table reference
     */
    public PurityReforgeBias() {
        this(DSL.name("purity_reforge_bias"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PurityReforgeBiasRecord> getPrimaryKey() {
        return Keys.PURITY_REFORGE_BIAS_PKEY;
    }

    @Override
    public PurityReforgeBias as(String alias) {
        return new PurityReforgeBias(DSL.name(alias), this);
    }

    @Override
    public PurityReforgeBias as(Name alias) {
        return new PurityReforgeBias(alias, this);
    }

    @Override
    public PurityReforgeBias as(Table<?> alias) {
        return new PurityReforgeBias(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityReforgeBias rename(String name) {
        return new PurityReforgeBias(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityReforgeBias rename(Name name) {
        return new PurityReforgeBias(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityReforgeBias rename(Table<?> name) {
        return new PurityReforgeBias(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityReforgeBias where(Condition condition) {
        return new PurityReforgeBias(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityReforgeBias where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityReforgeBias where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityReforgeBias where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityReforgeBias where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityReforgeBias where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityReforgeBias where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityReforgeBias where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityReforgeBias whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityReforgeBias whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
