/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.PurityRuneSlotDistributionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurityRuneSlotDistributions extends TableImpl<PurityRuneSlotDistributionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.purity_rune_slot_distributions</code>
     */
    public static final PurityRuneSlotDistributions PURITY_RUNE_SLOT_DISTRIBUTIONS = new PurityRuneSlotDistributions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurityRuneSlotDistributionsRecord> getRecordType() {
        return PurityRuneSlotDistributionsRecord.class;
    }

    /**
     * The column <code>public.purity_rune_slot_distributions.purity</code>.
     */
    public final TableField<PurityRuneSlotDistributionsRecord, String> PURITY = createField(DSL.name("purity"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.purity_rune_slot_distributions.draft</code>.
     */
    public final TableField<PurityRuneSlotDistributionsRecord, JSONB> DRAFT = createField(DSL.name("draft"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.purity_rune_slot_distributions.published</code>.
     */
    public final TableField<PurityRuneSlotDistributionsRecord, JSONB> PUBLISHED = createField(DSL.name("published"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.purity_rune_slot_distributions.updated_at</code>.
     */
    public final TableField<PurityRuneSlotDistributionsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column
     * <code>public.purity_rune_slot_distributions.published_at</code>.
     */
    public final TableField<PurityRuneSlotDistributionsRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PurityRuneSlotDistributions(Name alias, Table<PurityRuneSlotDistributionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurityRuneSlotDistributions(Name alias, Table<PurityRuneSlotDistributionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purity_rune_slot_distributions</code>
     * table reference
     */
    public PurityRuneSlotDistributions(String alias) {
        this(DSL.name(alias), PURITY_RUNE_SLOT_DISTRIBUTIONS);
    }

    /**
     * Create an aliased <code>public.purity_rune_slot_distributions</code>
     * table reference
     */
    public PurityRuneSlotDistributions(Name alias) {
        this(alias, PURITY_RUNE_SLOT_DISTRIBUTIONS);
    }

    /**
     * Create a <code>public.purity_rune_slot_distributions</code> table
     * reference
     */
    public PurityRuneSlotDistributions() {
        this(DSL.name("purity_rune_slot_distributions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PurityRuneSlotDistributionsRecord> getPrimaryKey() {
        return Keys.PURITY_RUNE_SLOT_DISTRIBUTIONS_PKEY;
    }

    @Override
    public PurityRuneSlotDistributions as(String alias) {
        return new PurityRuneSlotDistributions(DSL.name(alias), this);
    }

    @Override
    public PurityRuneSlotDistributions as(Name alias) {
        return new PurityRuneSlotDistributions(alias, this);
    }

    @Override
    public PurityRuneSlotDistributions as(Table<?> alias) {
        return new PurityRuneSlotDistributions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityRuneSlotDistributions rename(String name) {
        return new PurityRuneSlotDistributions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityRuneSlotDistributions rename(Name name) {
        return new PurityRuneSlotDistributions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurityRuneSlotDistributions rename(Table<?> name) {
        return new PurityRuneSlotDistributions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityRuneSlotDistributions where(Condition condition) {
        return new PurityRuneSlotDistributions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityRuneSlotDistributions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityRuneSlotDistributions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityRuneSlotDistributions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityRuneSlotDistributions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityRuneSlotDistributions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityRuneSlotDistributions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurityRuneSlotDistributions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityRuneSlotDistributions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurityRuneSlotDistributions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
