/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.QuestNpcsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestNpcs extends TableImpl<QuestNpcsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quest_npcs</code>
     */
    public static final QuestNpcs QUEST_NPCS = new QuestNpcs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestNpcsRecord> getRecordType() {
        return QuestNpcsRecord.class;
    }

    /**
     * The column <code>public.quest_npcs.id</code>.
     */
    public final TableField<QuestNpcsRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_npcs.display_name</code>.
     */
    public final TableField<QuestNpcsRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'NPC'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.quest_npcs.source</code>.
     */
    public final TableField<QuestNpcsRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'human'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.quest_npcs.factory</code>.
     */
    public final TableField<QuestNpcsRecord, String> FACTORY = createField(DSL.name("factory"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.quest_npcs.type</code>.
     */
    public final TableField<QuestNpcsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.quest_npcs.skin_value</code>.
     */
    public final TableField<QuestNpcsRecord, String> SKIN_VALUE = createField(DSL.name("skin_value"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.quest_npcs.skin_signature</code>.
     */
    public final TableField<QuestNpcsRecord, String> SKIN_SIGNATURE = createField(DSL.name("skin_signature"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.quest_npcs.updated_at</code>.
     */
    public final TableField<QuestNpcsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private QuestNpcs(Name alias, Table<QuestNpcsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private QuestNpcs(Name alias, Table<QuestNpcsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quest_npcs</code> table reference
     */
    public QuestNpcs(String alias) {
        this(DSL.name(alias), QUEST_NPCS);
    }

    /**
     * Create an aliased <code>public.quest_npcs</code> table reference
     */
    public QuestNpcs(Name alias) {
        this(alias, QUEST_NPCS);
    }

    /**
     * Create a <code>public.quest_npcs</code> table reference
     */
    public QuestNpcs() {
        this(DSL.name("quest_npcs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuestNpcsRecord> getPrimaryKey() {
        return Keys.QUEST_NPCS_PKEY;
    }

    @Override
    public QuestNpcs as(String alias) {
        return new QuestNpcs(DSL.name(alias), this);
    }

    @Override
    public QuestNpcs as(Name alias) {
        return new QuestNpcs(alias, this);
    }

    @Override
    public QuestNpcs as(Table<?> alias) {
        return new QuestNpcs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestNpcs rename(String name) {
        return new QuestNpcs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestNpcs rename(Name name) {
        return new QuestNpcs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestNpcs rename(Table<?> name) {
        return new QuestNpcs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestNpcs where(Condition condition) {
        return new QuestNpcs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestNpcs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestNpcs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestNpcs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestNpcs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestNpcs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestNpcs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestNpcs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestNpcs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestNpcs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
