/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.QuestFlagsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestFlags extends TableImpl<QuestFlagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quest_flags</code>
     */
    public static final QuestFlags QUEST_FLAGS = new QuestFlags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestFlagsRecord> getRecordType() {
        return QuestFlagsRecord.class;
    }

    /**
     * The column <code>public.quest_flags.scope_type</code>.
     */
    public final TableField<QuestFlagsRecord, String> SCOPE_TYPE = createField(DSL.name("scope_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_flags.scope_id</code>.
     */
    public final TableField<QuestFlagsRecord, String> SCOPE_ID = createField(DSL.name("scope_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_flags.flag</code>.
     */
    public final TableField<QuestFlagsRecord, String> FLAG = createField(DSL.name("flag"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_flags.value</code>.
     */
    public final TableField<QuestFlagsRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB, this, "");

    private QuestFlags(Name alias, Table<QuestFlagsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private QuestFlags(Name alias, Table<QuestFlagsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quest_flags</code> table reference
     */
    public QuestFlags(String alias) {
        this(DSL.name(alias), QUEST_FLAGS);
    }

    /**
     * Create an aliased <code>public.quest_flags</code> table reference
     */
    public QuestFlags(Name alias) {
        this(alias, QUEST_FLAGS);
    }

    /**
     * Create a <code>public.quest_flags</code> table reference
     */
    public QuestFlags() {
        this(DSL.name("quest_flags"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuestFlagsRecord> getPrimaryKey() {
        return Keys.QUEST_FLAGS_PKEY;
    }

    @Override
    public QuestFlags as(String alias) {
        return new QuestFlags(DSL.name(alias), this);
    }

    @Override
    public QuestFlags as(Name alias) {
        return new QuestFlags(alias, this);
    }

    @Override
    public QuestFlags as(Table<?> alias) {
        return new QuestFlags(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestFlags rename(String name) {
        return new QuestFlags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestFlags rename(Name name) {
        return new QuestFlags(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestFlags rename(Table<?> name) {
        return new QuestFlags(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestFlags where(Condition condition) {
        return new QuestFlags(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestFlags where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestFlags where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestFlags where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestFlags where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestFlags where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestFlags where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestFlags where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestFlags whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestFlags whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
