/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.QuestInstances.QuestInstancesPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.QuestObjectiveProgressRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestObjectiveProgress extends TableImpl<QuestObjectiveProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quest_objective_progress</code>
     */
    public static final QuestObjectiveProgress QUEST_OBJECTIVE_PROGRESS = new QuestObjectiveProgress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestObjectiveProgressRecord> getRecordType() {
        return QuestObjectiveProgressRecord.class;
    }

    /**
     * The column <code>public.quest_objective_progress.instance_id</code>.
     */
    public final TableField<QuestObjectiveProgressRecord, UUID> INSTANCE_ID = createField(DSL.name("instance_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.quest_objective_progress.objective_key</code>.
     */
    public final TableField<QuestObjectiveProgressRecord, String> OBJECTIVE_KEY = createField(DSL.name("objective_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_objective_progress.progress</code>.
     */
    public final TableField<QuestObjectiveProgressRecord, Integer> PROGRESS = createField(DSL.name("progress"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.quest_objective_progress.target</code>.
     */
    public final TableField<QuestObjectiveProgressRecord, Integer> TARGET = createField(DSL.name("target"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private QuestObjectiveProgress(Name alias, Table<QuestObjectiveProgressRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private QuestObjectiveProgress(Name alias, Table<QuestObjectiveProgressRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quest_objective_progress</code> table
     * reference
     */
    public QuestObjectiveProgress(String alias) {
        this(DSL.name(alias), QUEST_OBJECTIVE_PROGRESS);
    }

    /**
     * Create an aliased <code>public.quest_objective_progress</code> table
     * reference
     */
    public QuestObjectiveProgress(Name alias) {
        this(alias, QUEST_OBJECTIVE_PROGRESS);
    }

    /**
     * Create a <code>public.quest_objective_progress</code> table reference
     */
    public QuestObjectiveProgress() {
        this(DSL.name("quest_objective_progress"), null);
    }

    public <O extends Record> QuestObjectiveProgress(Table<O> path, ForeignKey<O, QuestObjectiveProgressRecord> childPath, InverseForeignKey<O, QuestObjectiveProgressRecord> parentPath) {
        super(path, childPath, parentPath, QUEST_OBJECTIVE_PROGRESS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class QuestObjectiveProgressPath extends QuestObjectiveProgress implements Path<QuestObjectiveProgressRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> QuestObjectiveProgressPath(Table<O> path, ForeignKey<O, QuestObjectiveProgressRecord> childPath, InverseForeignKey<O, QuestObjectiveProgressRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private QuestObjectiveProgressPath(Name alias, Table<QuestObjectiveProgressRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public QuestObjectiveProgressPath as(String alias) {
            return new QuestObjectiveProgressPath(DSL.name(alias), this);
        }

        @Override
        public QuestObjectiveProgressPath as(Name alias) {
            return new QuestObjectiveProgressPath(alias, this);
        }

        @Override
        public QuestObjectiveProgressPath as(Table<?> alias) {
            return new QuestObjectiveProgressPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuestObjectiveProgressRecord> getPrimaryKey() {
        return Keys.QUEST_OBJECTIVE_PROGRESS_PKEY;
    }

    @Override
    public List<ForeignKey<QuestObjectiveProgressRecord, ?>> getReferences() {
        return Arrays.asList(Keys.QUEST_OBJECTIVE_PROGRESS__QUEST_OBJECTIVE_PROGRESS_INSTANCE_ID_FKEY);
    }

    private transient QuestInstancesPath _questInstances;

    /**
     * Get the implicit join path to the <code>public.quest_instances</code>
     * table.
     */
    public QuestInstancesPath questInstances() {
        if (_questInstances == null)
            _questInstances = new QuestInstancesPath(this, Keys.QUEST_OBJECTIVE_PROGRESS__QUEST_OBJECTIVE_PROGRESS_INSTANCE_ID_FKEY, null);

        return _questInstances;
    }

    @Override
    public QuestObjectiveProgress as(String alias) {
        return new QuestObjectiveProgress(DSL.name(alias), this);
    }

    @Override
    public QuestObjectiveProgress as(Name alias) {
        return new QuestObjectiveProgress(alias, this);
    }

    @Override
    public QuestObjectiveProgress as(Table<?> alias) {
        return new QuestObjectiveProgress(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestObjectiveProgress rename(String name) {
        return new QuestObjectiveProgress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestObjectiveProgress rename(Name name) {
        return new QuestObjectiveProgress(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestObjectiveProgress rename(Table<?> name) {
        return new QuestObjectiveProgress(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestObjectiveProgress where(Condition condition) {
        return new QuestObjectiveProgress(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestObjectiveProgress where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestObjectiveProgress where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestObjectiveProgress where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestObjectiveProgress where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestObjectiveProgress where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestObjectiveProgress where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestObjectiveProgress where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestObjectiveProgress whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestObjectiveProgress whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
