/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.QuestPrimitivesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestPrimitives extends TableImpl<QuestPrimitivesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quest_primitives</code>
     */
    public static final QuestPrimitives QUEST_PRIMITIVES = new QuestPrimitives();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestPrimitivesRecord> getRecordType() {
        return QuestPrimitivesRecord.class;
    }

    /**
     * The column <code>public.quest_primitives.id</code>.
     */
    public final TableField<QuestPrimitivesRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_primitives.category</code>.
     */
    public final TableField<QuestPrimitivesRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_primitives.label</code>.
     */
    public final TableField<QuestPrimitivesRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_primitives.param_schema</code>.
     */
    public final TableField<QuestPrimitivesRecord, JSONB> PARAM_SCHEMA = createField(DSL.name("param_schema"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.quest_primitives.ui</code>.
     */
    public final TableField<QuestPrimitivesRecord, JSONB> UI = createField(DSL.name("ui"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    private QuestPrimitives(Name alias, Table<QuestPrimitivesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private QuestPrimitives(Name alias, Table<QuestPrimitivesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quest_primitives</code> table reference
     */
    public QuestPrimitives(String alias) {
        this(DSL.name(alias), QUEST_PRIMITIVES);
    }

    /**
     * Create an aliased <code>public.quest_primitives</code> table reference
     */
    public QuestPrimitives(Name alias) {
        this(alias, QUEST_PRIMITIVES);
    }

    /**
     * Create a <code>public.quest_primitives</code> table reference
     */
    public QuestPrimitives() {
        this(DSL.name("quest_primitives"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuestPrimitivesRecord> getPrimaryKey() {
        return Keys.QUEST_PRIMITIVES_PKEY;
    }

    @Override
    public QuestPrimitives as(String alias) {
        return new QuestPrimitives(DSL.name(alias), this);
    }

    @Override
    public QuestPrimitives as(Name alias) {
        return new QuestPrimitives(alias, this);
    }

    @Override
    public QuestPrimitives as(Table<?> alias) {
        return new QuestPrimitives(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestPrimitives rename(String name) {
        return new QuestPrimitives(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestPrimitives rename(Name name) {
        return new QuestPrimitives(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestPrimitives rename(Table<?> name) {
        return new QuestPrimitives(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestPrimitives where(Condition condition) {
        return new QuestPrimitives(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestPrimitives where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestPrimitives where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestPrimitives where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestPrimitives where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestPrimitives where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestPrimitives where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestPrimitives where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestPrimitives whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestPrimitives whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
