/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.QuestObjectiveProgress.QuestObjectiveProgressPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.QuestInstancesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestInstances extends TableImpl<QuestInstancesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quest_instances</code>
     */
    public static final QuestInstances QUEST_INSTANCES = new QuestInstances();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestInstancesRecord> getRecordType() {
        return QuestInstancesRecord.class;
    }

    /**
     * The column <code>public.quest_instances.id</code>.
     */
    public final TableField<QuestInstancesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.quest_instances.quest_id</code>.
     */
    public final TableField<QuestInstancesRecord, String> QUEST_ID = createField(DSL.name("quest_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_instances.scope_type</code>.
     */
    public final TableField<QuestInstancesRecord, String> SCOPE_TYPE = createField(DSL.name("scope_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_instances.scope_id</code>.
     */
    public final TableField<QuestInstancesRecord, String> SCOPE_ID = createField(DSL.name("scope_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.quest_instances.status</code>.
     */
    public final TableField<QuestInstancesRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'active'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.quest_instances.current_stages</code>.
     */
    public final TableField<QuestInstancesRecord, JSONB> CURRENT_STAGES = createField(DSL.name("current_stages"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.quest_instances.started_at</code>.
     */
    public final TableField<QuestInstancesRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.quest_instances.updated_at</code>.
     */
    public final TableField<QuestInstancesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private QuestInstances(Name alias, Table<QuestInstancesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private QuestInstances(Name alias, Table<QuestInstancesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quest_instances</code> table reference
     */
    public QuestInstances(String alias) {
        this(DSL.name(alias), QUEST_INSTANCES);
    }

    /**
     * Create an aliased <code>public.quest_instances</code> table reference
     */
    public QuestInstances(Name alias) {
        this(alias, QUEST_INSTANCES);
    }

    /**
     * Create a <code>public.quest_instances</code> table reference
     */
    public QuestInstances() {
        this(DSL.name("quest_instances"), null);
    }

    public <O extends Record> QuestInstances(Table<O> path, ForeignKey<O, QuestInstancesRecord> childPath, InverseForeignKey<O, QuestInstancesRecord> parentPath) {
        super(path, childPath, parentPath, QUEST_INSTANCES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class QuestInstancesPath extends QuestInstances implements Path<QuestInstancesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> QuestInstancesPath(Table<O> path, ForeignKey<O, QuestInstancesRecord> childPath, InverseForeignKey<O, QuestInstancesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private QuestInstancesPath(Name alias, Table<QuestInstancesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public QuestInstancesPath as(String alias) {
            return new QuestInstancesPath(DSL.name(alias), this);
        }

        @Override
        public QuestInstancesPath as(Name alias) {
            return new QuestInstancesPath(alias, this);
        }

        @Override
        public QuestInstancesPath as(Table<?> alias) {
            return new QuestInstancesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.QUEST_INSTANCES_SCOPE_IDX);
    }

    @Override
    public UniqueKey<QuestInstancesRecord> getPrimaryKey() {
        return Keys.QUEST_INSTANCES_PKEY;
    }

    @Override
    public List<UniqueKey<QuestInstancesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.QUEST_INSTANCES_QUEST_ID_SCOPE_TYPE_SCOPE_ID_KEY);
    }

    private transient QuestObjectiveProgressPath _questObjectiveProgress;

    /**
     * Get the implicit to-many join path to the
     * <code>public.quest_objective_progress</code> table
     */
    public QuestObjectiveProgressPath questObjectiveProgress() {
        if (_questObjectiveProgress == null)
            _questObjectiveProgress = new QuestObjectiveProgressPath(this, null, Keys.QUEST_OBJECTIVE_PROGRESS__QUEST_OBJECTIVE_PROGRESS_INSTANCE_ID_FKEY.getInverseKey());

        return _questObjectiveProgress;
    }

    @Override
    public QuestInstances as(String alias) {
        return new QuestInstances(DSL.name(alias), this);
    }

    @Override
    public QuestInstances as(Name alias) {
        return new QuestInstances(alias, this);
    }

    @Override
    public QuestInstances as(Table<?> alias) {
        return new QuestInstances(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestInstances rename(String name) {
        return new QuestInstances(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestInstances rename(Name name) {
        return new QuestInstances(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestInstances rename(Table<?> name) {
        return new QuestInstances(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestInstances where(Condition condition) {
        return new QuestInstances(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestInstances where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestInstances where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestInstances where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestInstances where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestInstances where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestInstances where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuestInstances where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestInstances whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuestInstances whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
