/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.Zones.ZonesPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ZoneDiscoveriesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ZoneDiscoveries extends TableImpl<ZoneDiscoveriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.zone_discoveries</code>
     */
    public static final ZoneDiscoveries ZONE_DISCOVERIES = new ZoneDiscoveries();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ZoneDiscoveriesRecord> getRecordType() {
        return ZoneDiscoveriesRecord.class;
    }

    /**
     * The column <code>public.zone_discoveries.id</code>.
     */
    public final TableField<ZoneDiscoveriesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.zone_discoveries.client</code>.
     */
    public final TableField<ZoneDiscoveriesRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.zone_discoveries.zone_id</code>.
     */
    public final TableField<ZoneDiscoveriesRecord, Long> ZONE_ID = createField(DSL.name("zone_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.zone_discoveries.discovered_at</code>.
     */
    public final TableField<ZoneDiscoveriesRecord, LocalDateTime> DISCOVERED_AT = createField(DSL.name("discovered_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ZoneDiscoveries(Name alias, Table<ZoneDiscoveriesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ZoneDiscoveries(Name alias, Table<ZoneDiscoveriesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.zone_discoveries</code> table reference
     */
    public ZoneDiscoveries(String alias) {
        this(DSL.name(alias), ZONE_DISCOVERIES);
    }

    /**
     * Create an aliased <code>public.zone_discoveries</code> table reference
     */
    public ZoneDiscoveries(Name alias) {
        this(alias, ZONE_DISCOVERIES);
    }

    /**
     * Create a <code>public.zone_discoveries</code> table reference
     */
    public ZoneDiscoveries() {
        this(DSL.name("zone_discoveries"), null);
    }

    public <O extends Record> ZoneDiscoveries(Table<O> path, ForeignKey<O, ZoneDiscoveriesRecord> childPath, InverseForeignKey<O, ZoneDiscoveriesRecord> parentPath) {
        super(path, childPath, parentPath, ZONE_DISCOVERIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ZoneDiscoveriesPath extends ZoneDiscoveries implements Path<ZoneDiscoveriesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ZoneDiscoveriesPath(Table<O> path, ForeignKey<O, ZoneDiscoveriesRecord> childPath, InverseForeignKey<O, ZoneDiscoveriesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ZoneDiscoveriesPath(Name alias, Table<ZoneDiscoveriesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ZoneDiscoveriesPath as(String alias) {
            return new ZoneDiscoveriesPath(DSL.name(alias), this);
        }

        @Override
        public ZoneDiscoveriesPath as(Name alias) {
            return new ZoneDiscoveriesPath(alias, this);
        }

        @Override
        public ZoneDiscoveriesPath as(Table<?> alias) {
            return new ZoneDiscoveriesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ZONE_DISCOVERIES_CLIENT);
    }

    @Override
    public Identity<ZoneDiscoveriesRecord, Long> getIdentity() {
        return (Identity<ZoneDiscoveriesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ZoneDiscoveriesRecord> getPrimaryKey() {
        return Keys.ZONE_DISCOVERIES_PKEY;
    }

    @Override
    public List<UniqueKey<ZoneDiscoveriesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_ZONE_DISCOVERY);
    }

    @Override
    public List<ForeignKey<ZoneDiscoveriesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ZONE_DISCOVERIES__ZONE_DISCOVERIES_CLIENT_FKEY, Keys.ZONE_DISCOVERIES__ZONE_DISCOVERIES_ZONE_ID_FKEY);
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit join path to the <code>public.clients</code> table.
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, Keys.ZONE_DISCOVERIES__ZONE_DISCOVERIES_CLIENT_FKEY, null);

        return _clients;
    }

    private transient ZonesPath _zones;

    /**
     * Get the implicit join path to the <code>public.zones</code> table.
     */
    public ZonesPath zones() {
        if (_zones == null)
            _zones = new ZonesPath(this, Keys.ZONE_DISCOVERIES__ZONE_DISCOVERIES_ZONE_ID_FKEY, null);

        return _zones;
    }

    @Override
    public ZoneDiscoveries as(String alias) {
        return new ZoneDiscoveries(DSL.name(alias), this);
    }

    @Override
    public ZoneDiscoveries as(Name alias) {
        return new ZoneDiscoveries(alias, this);
    }

    @Override
    public ZoneDiscoveries as(Table<?> alias) {
        return new ZoneDiscoveries(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ZoneDiscoveries rename(String name) {
        return new ZoneDiscoveries(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ZoneDiscoveries rename(Name name) {
        return new ZoneDiscoveries(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ZoneDiscoveries rename(Table<?> name) {
        return new ZoneDiscoveries(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneDiscoveries where(Condition condition) {
        return new ZoneDiscoveries(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneDiscoveries where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneDiscoveries where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneDiscoveries where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneDiscoveries where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneDiscoveries where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneDiscoveries where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneDiscoveries where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneDiscoveries whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneDiscoveries whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
