/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.ZoneDiscoveries.ZoneDiscoveriesPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ZonesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Zones extends TableImpl<ZonesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.zones</code>
     */
    public static final Zones ZONES = new Zones();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ZonesRecord> getRecordType() {
        return ZonesRecord.class;
    }

    /**
     * The column <code>public.zones.id</code>.
     */
    public final TableField<ZonesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.zones.zone_key</code>.
     */
    public final TableField<ZonesRecord, String> ZONE_KEY = createField(DSL.name("zone_key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.zones.display_name</code>.
     */
    public final TableField<ZonesRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Zones(Name alias, Table<ZonesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Zones(Name alias, Table<ZonesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.zones</code> table reference
     */
    public Zones(String alias) {
        this(DSL.name(alias), ZONES);
    }

    /**
     * Create an aliased <code>public.zones</code> table reference
     */
    public Zones(Name alias) {
        this(alias, ZONES);
    }

    /**
     * Create a <code>public.zones</code> table reference
     */
    public Zones() {
        this(DSL.name("zones"), null);
    }

    public <O extends Record> Zones(Table<O> path, ForeignKey<O, ZonesRecord> childPath, InverseForeignKey<O, ZonesRecord> parentPath) {
        super(path, childPath, parentPath, ZONES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ZonesPath extends Zones implements Path<ZonesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ZonesPath(Table<O> path, ForeignKey<O, ZonesRecord> childPath, InverseForeignKey<O, ZonesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ZonesPath(Name alias, Table<ZonesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ZonesPath as(String alias) {
            return new ZonesPath(DSL.name(alias), this);
        }

        @Override
        public ZonesPath as(Name alias) {
            return new ZonesPath(alias, this);
        }

        @Override
        public ZonesPath as(Table<?> alias) {
            return new ZonesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ZonesRecord> getPrimaryKey() {
        return Keys.ZONES_PKEY;
    }

    @Override
    public List<UniqueKey<ZonesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ZONES_ZONE_KEY_KEY);
    }

    private transient ZoneDiscoveriesPath _zoneDiscoveries;

    /**
     * Get the implicit to-many join path to the
     * <code>public.zone_discoveries</code> table
     */
    public ZoneDiscoveriesPath zoneDiscoveries() {
        if (_zoneDiscoveries == null)
            _zoneDiscoveries = new ZoneDiscoveriesPath(this, null, Keys.ZONE_DISCOVERIES__ZONE_DISCOVERIES_ZONE_ID_FKEY.getInverseKey());

        return _zoneDiscoveries;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.clients</code> table
     */
    public ClientsPath clients() {
        return zoneDiscoveries().clients();
    }

    @Override
    public Zones as(String alias) {
        return new Zones(DSL.name(alias), this);
    }

    @Override
    public Zones as(Name alias) {
        return new Zones(alias, this);
    }

    @Override
    public Zones as(Table<?> alias) {
        return new Zones(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Zones rename(String name) {
        return new Zones(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Zones rename(Name name) {
        return new Zones(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Zones rename(Table<?> name) {
        return new Zones(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Zones where(Condition condition) {
        return new Zones(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Zones where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Zones where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Zones where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Zones where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Zones where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Zones where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Zones where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Zones whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Zones whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
