/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimBuildRecord extends UpdatableRecordImpl<SimBuildRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_build.id</code>.
     */
    public SimBuildRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_build.run_id</code>.
     */
    public SimBuildRecord setRunId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sim_build.role</code>.
     */
    public SimBuildRecord setRole(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.sim_build.weapon</code>.
     */
    public SimBuildRecord setWeapon(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon</code>.
     */
    public String getWeapon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sim_build.runes</code>.
     */
    public SimBuildRecord setRunes(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.runes</code>.
     */
    public JSONB getRunes() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.sim_build.skills</code>.
     */
    public SimBuildRecord setSkills(JSONB value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.skills</code>.
     */
    public JSONB getSkills() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.sim_build.points_spent</code>.
     */
    public SimBuildRecord setPointsSpent(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.points_spent</code>.
     */
    public Integer getPointsSpent() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.sim_build.booster</code>.
     */
    public SimBuildRecord setBooster(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.booster</code>.
     */
    public Boolean getBooster() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.sim_build.fingerprint</code>.
     */
    public SimBuildRecord setFingerprint(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.fingerprint</code>.
     */
    public String getFingerprint() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.sim_build.weapon_damage_base</code>.
     */
    public SimBuildRecord setWeaponDamageBase(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_damage_base</code>.
     */
    public BigDecimal getWeaponDamageBase() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.sim_build.weapon_damage_min</code>.
     */
    public SimBuildRecord setWeaponDamageMin(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_damage_min</code>.
     */
    public BigDecimal getWeaponDamageMin() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.sim_build.weapon_damage_max</code>.
     */
    public SimBuildRecord setWeaponDamageMax(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_damage_max</code>.
     */
    public BigDecimal getWeaponDamageMax() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.sim_build.weapon_attack_speed_base</code>.
     */
    public SimBuildRecord setWeaponAttackSpeedBase(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_attack_speed_base</code>.
     */
    public BigDecimal getWeaponAttackSpeedBase() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>public.sim_build.weapon_attack_speed_min</code>.
     */
    public SimBuildRecord setWeaponAttackSpeedMin(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_attack_speed_min</code>.
     */
    public BigDecimal getWeaponAttackSpeedMin() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>public.sim_build.weapon_attack_speed_max</code>.
     */
    public SimBuildRecord setWeaponAttackSpeedMax(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_attack_speed_max</code>.
     */
    public BigDecimal getWeaponAttackSpeedMax() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>public.sim_build.weapon_slot</code>.
     */
    public SimBuildRecord setWeaponSlot(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_slot</code>.
     */
    public String getWeaponSlot() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.sim_build.weapon_aliases</code>.
     */
    public SimBuildRecord setWeaponAliases(JSONB value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_aliases</code>.
     */
    public JSONB getWeaponAliases() {
        return (JSONB) get(16);
    }

    /**
     * Setter for <code>public.sim_build.weapon_roll</code>.
     */
    public SimBuildRecord setWeaponRoll(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_build.weapon_roll</code>.
     */
    public String getWeaponRoll() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimBuildRecord
     */
    public SimBuildRecord() {
        super(SimBuild.SIM_BUILD);
    }

    /**
     * Create a detached, initialised SimBuildRecord
     */
    public SimBuildRecord(Long id, Long runId, String role, String weapon, JSONB runes, JSONB skills, Integer pointsSpent, Boolean booster, String fingerprint, BigDecimal weaponDamageBase, BigDecimal weaponDamageMin, BigDecimal weaponDamageMax, BigDecimal weaponAttackSpeedBase, BigDecimal weaponAttackSpeedMin, BigDecimal weaponAttackSpeedMax, String weaponSlot, JSONB weaponAliases, String weaponRoll) {
        super(SimBuild.SIM_BUILD);

        setId(id);
        setRunId(runId);
        setRole(role);
        setWeapon(weapon);
        setRunes(runes);
        setSkills(skills);
        setPointsSpent(pointsSpent);
        setBooster(booster);
        setFingerprint(fingerprint);
        setWeaponDamageBase(weaponDamageBase);
        setWeaponDamageMin(weaponDamageMin);
        setWeaponDamageMax(weaponDamageMax);
        setWeaponAttackSpeedBase(weaponAttackSpeedBase);
        setWeaponAttackSpeedMin(weaponAttackSpeedMin);
        setWeaponAttackSpeedMax(weaponAttackSpeedMax);
        setWeaponSlot(weaponSlot);
        setWeaponAliases(weaponAliases);
        setWeaponRoll(weaponRoll);
        resetChangedOnNotNull();
    }
}
