/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimDeltaPlan;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimDeltaPlanRecord extends TableRecordImpl<SimDeltaPlanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_delta_plan.run_id</code>.
     */
    public SimDeltaPlanRecord setRunId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_delta_plan.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_delta_plan.fingerprint</code>.
     */
    public SimDeltaPlanRecord setFingerprint(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_delta_plan.fingerprint</code>.
     */
    public String getFingerprint() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.sim_delta_plan.target_role</code>.
     */
    public SimDeltaPlanRecord setTargetRole(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_delta_plan.target_role</code>.
     */
    public String getTargetRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.sim_delta_plan.target_armor</code>.
     */
    public SimDeltaPlanRecord setTargetArmor(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_delta_plan.target_armor</code>.
     */
    public String getTargetArmor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sim_delta_plan.config_scope_hash</code>.
     */
    public SimDeltaPlanRecord setConfigScopeHash(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_delta_plan.config_scope_hash</code>.
     */
    public String getConfigScopeHash() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimDeltaPlanRecord
     */
    public SimDeltaPlanRecord() {
        super(SimDeltaPlan.SIM_DELTA_PLAN);
    }

    /**
     * Create a detached, initialised SimDeltaPlanRecord
     */
    public SimDeltaPlanRecord(Long runId, String fingerprint, String targetRole, String targetArmor, String configScopeHash) {
        super(SimDeltaPlan.SIM_DELTA_PLAN);

        setRunId(runId);
        setFingerprint(fingerprint);
        setTargetRole(targetRole);
        setTargetArmor(targetArmor);
        setConfigScopeHash(configScopeHash);
        resetChangedOnNotNull();
    }
}
