/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimDuelDiagnostic;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimDuelDiagnosticRecord extends UpdatableRecordImpl<SimDuelDiagnosticRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_duel_diagnostic.id</code>.
     */
    public SimDuelDiagnosticRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.run_id</code>.
     */
    public SimDuelDiagnosticRecord setRunId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.build_id</code>.
     */
    public SimDuelDiagnosticRecord setBuildId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.build_id</code>.
     */
    public Long getBuildId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.target_role</code>.
     */
    public SimDuelDiagnosticRecord setTargetRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.target_role</code>.
     */
    public String getTargetRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.target_armor</code>.
     */
    public SimDuelDiagnosticRecord setTargetArmor(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.target_armor</code>.
     */
    public String getTargetArmor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.iteration</code>.
     */
    public SimDuelDiagnosticRecord setIteration(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.iteration</code>.
     */
    public Integer getIteration() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.arena_index</code>.
     */
    public SimDuelDiagnosticRecord setArenaIndex(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.arena_index</code>.
     */
    public Integer getArenaIndex() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_duels_fought</code>.
     */
    public SimDuelDiagnosticRecord setAttackerDuelsFought(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_duels_fought</code>.
     */
    public Integer getAttackerDuelsFought() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_duels_fought</code>.
     */
    public SimDuelDiagnosticRecord setDefenderDuelsFought(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_duels_fought</code>.
     */
    public Integer getDefenderDuelsFought() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_revives</code>.
     */
    public SimDuelDiagnosticRecord setAttackerRevives(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_revives</code>.
     */
    public Integer getAttackerRevives() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_revives</code>.
     */
    public SimDuelDiagnosticRecord setDefenderRevives(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_revives</code>.
     */
    public Integer getDefenderRevives() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_ever_died</code>.
     */
    public SimDuelDiagnosticRecord setAttackerEverDied(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_ever_died</code>.
     */
    public Boolean getAttackerEverDied() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_ever_died</code>.
     */
    public SimDuelDiagnosticRecord setDefenderEverDied(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_ever_died</code>.
     */
    public Boolean getDefenderEverDied() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.outcome</code>.
     */
    public SimDuelDiagnosticRecord setOutcome(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.outcome</code>.
     */
    public String getOutcome() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.resolved_tick</code>.
     */
    public SimDuelDiagnosticRecord setResolvedTick(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.resolved_tick</code>.
     */
    public Integer getResolvedTick() {
        return (Integer) get(14);
    }

    /**
     * Setter for
     * <code>public.sim_duel_diagnostic.attacker_first_hit_tick</code>.
     */
    public SimDuelDiagnosticRecord setAttackerFirstHitTick(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.sim_duel_diagnostic.attacker_first_hit_tick</code>.
     */
    public Integer getAttackerFirstHitTick() {
        return (Integer) get(15);
    }

    /**
     * Setter for
     * <code>public.sim_duel_diagnostic.defender_first_hit_tick</code>.
     */
    public SimDuelDiagnosticRecord setDefenderFirstHitTick(Integer value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.sim_duel_diagnostic.defender_first_hit_tick</code>.
     */
    public Integer getDefenderFirstHitTick() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_hits</code>.
     */
    public SimDuelDiagnosticRecord setAttackerHits(Integer value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_hits</code>.
     */
    public Integer getAttackerHits() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_hits</code>.
     */
    public SimDuelDiagnosticRecord setDefenderHits(Integer value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_hits</code>.
     */
    public Integer getDefenderHits() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_damage</code>.
     */
    public SimDuelDiagnosticRecord setAttackerDamage(BigDecimal value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_damage</code>.
     */
    public BigDecimal getAttackerDamage() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_damage</code>.
     */
    public SimDuelDiagnosticRecord setDefenderDamage(BigDecimal value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_damage</code>.
     */
    public BigDecimal getDefenderDamage() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_start_health</code>.
     */
    public SimDuelDiagnosticRecord setAttackerStartHealth(BigDecimal value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_start_health</code>.
     */
    public BigDecimal getAttackerStartHealth() {
        return (BigDecimal) get(21);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_max_health</code>.
     */
    public SimDuelDiagnosticRecord setAttackerMaxHealth(BigDecimal value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_max_health</code>.
     */
    public BigDecimal getAttackerMaxHealth() {
        return (BigDecimal) get(22);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_start_health</code>.
     */
    public SimDuelDiagnosticRecord setDefenderStartHealth(BigDecimal value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_start_health</code>.
     */
    public BigDecimal getDefenderStartHealth() {
        return (BigDecimal) get(23);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_max_health</code>.
     */
    public SimDuelDiagnosticRecord setDefenderMaxHealth(BigDecimal value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_max_health</code>.
     */
    public BigDecimal getDefenderMaxHealth() {
        return (BigDecimal) get(24);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.attacker_end_health</code>.
     */
    public SimDuelDiagnosticRecord setAttackerEndHealth(BigDecimal value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.attacker_end_health</code>.
     */
    public BigDecimal getAttackerEndHealth() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.defender_end_health</code>.
     */
    public SimDuelDiagnosticRecord setDefenderEndHealth(BigDecimal value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.defender_end_health</code>.
     */
    public BigDecimal getDefenderEndHealth() {
        return (BigDecimal) get(26);
    }

    /**
     * Setter for <code>public.sim_duel_diagnostic.detail</code>.
     */
    public SimDuelDiagnosticRecord setDetail(JSONB value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_duel_diagnostic.detail</code>.
     */
    public JSONB getDetail() {
        return (JSONB) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimDuelDiagnosticRecord
     */
    public SimDuelDiagnosticRecord() {
        super(SimDuelDiagnostic.SIM_DUEL_DIAGNOSTIC);
    }

    /**
     * Create a detached, initialised SimDuelDiagnosticRecord
     */
    public SimDuelDiagnosticRecord(Long id, Long runId, Long buildId, String targetRole, String targetArmor, Integer iteration, Integer arenaIndex, Integer attackerDuelsFought, Integer defenderDuelsFought, Integer attackerRevives, Integer defenderRevives, Boolean attackerEverDied, Boolean defenderEverDied, String outcome, Integer resolvedTick, Integer attackerFirstHitTick, Integer defenderFirstHitTick, Integer attackerHits, Integer defenderHits, BigDecimal attackerDamage, BigDecimal defenderDamage, BigDecimal attackerStartHealth, BigDecimal attackerMaxHealth, BigDecimal defenderStartHealth, BigDecimal defenderMaxHealth, BigDecimal attackerEndHealth, BigDecimal defenderEndHealth, JSONB detail) {
        super(SimDuelDiagnostic.SIM_DUEL_DIAGNOSTIC);

        setId(id);
        setRunId(runId);
        setBuildId(buildId);
        setTargetRole(targetRole);
        setTargetArmor(targetArmor);
        setIteration(iteration);
        setArenaIndex(arenaIndex);
        setAttackerDuelsFought(attackerDuelsFought);
        setDefenderDuelsFought(defenderDuelsFought);
        setAttackerRevives(attackerRevives);
        setDefenderRevives(defenderRevives);
        setAttackerEverDied(attackerEverDied);
        setDefenderEverDied(defenderEverDied);
        setOutcome(outcome);
        setResolvedTick(resolvedTick);
        setAttackerFirstHitTick(attackerFirstHitTick);
        setDefenderFirstHitTick(defenderFirstHitTick);
        setAttackerHits(attackerHits);
        setDefenderHits(defenderHits);
        setAttackerDamage(attackerDamage);
        setDefenderDamage(defenderDamage);
        setAttackerStartHealth(attackerStartHealth);
        setAttackerMaxHealth(attackerMaxHealth);
        setDefenderStartHealth(defenderStartHealth);
        setDefenderMaxHealth(defenderMaxHealth);
        setAttackerEndHealth(attackerEndHealth);
        setDefenderEndHealth(defenderEndHealth);
        setDetail(detail);
        resetChangedOnNotNull();
    }
}
