/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimResult;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimResultRecord extends UpdatableRecordImpl<SimResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_result.id</code>.
     */
    public SimResultRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_result.run_id</code>.
     */
    public SimResultRecord setRunId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sim_result.build_id</code>.
     */
    public SimResultRecord setBuildId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.build_id</code>.
     */
    public Long getBuildId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sim_result.target_role</code>.
     */
    public SimResultRecord setTargetRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.target_role</code>.
     */
    public String getTargetRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sim_result.target_armor</code>.
     */
    public SimResultRecord setTargetArmor(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.target_armor</code>.
     */
    public String getTargetArmor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sim_result.target_hp</code>.
     */
    public SimResultRecord setTargetHp(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.target_hp</code>.
     */
    public BigDecimal getTargetHp() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.sim_result.target_skills</code>.
     */
    public SimResultRecord setTargetSkills(JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.target_skills</code>.
     */
    public JSONB getTargetSkills() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.sim_result.target_points</code>.
     */
    public SimResultRecord setTargetPoints(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.target_points</code>.
     */
    public Integer getTargetPoints() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.sim_result.dmg_per_hit</code>.
     */
    public SimResultRecord setDmgPerHit(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.dmg_per_hit</code>.
     */
    public BigDecimal getDmgPerHit() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.sim_result.dps_sustained</code>.
     */
    public SimResultRecord setDpsSustained(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.dps_sustained</code>.
     */
    public BigDecimal getDpsSustained() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.sim_result.dps_burst</code>.
     */
    public SimResultRecord setDpsBurst(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.dps_burst</code>.
     */
    public BigDecimal getDpsBurst() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.sim_result.ttk_s</code>.
     */
    public SimResultRecord setTtkS(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.ttk_s</code>.
     */
    public BigDecimal getTtkS() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.sim_result.hits_to_kill</code>.
     */
    public SimResultRecord setHitsToKill(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.hits_to_kill</code>.
     */
    public BigDecimal getHitsToKill() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>public.sim_result.energy_limited</code>.
     */
    public SimResultRecord setEnergyLimited(Boolean value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.energy_limited</code>.
     */
    public Boolean getEnergyLimited() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.sim_result.extras</code>.
     */
    public SimResultRecord setExtras(JSONB value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_result.extras</code>.
     */
    public JSONB getExtras() {
        return (JSONB) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimResultRecord
     */
    public SimResultRecord() {
        super(SimResult.SIM_RESULT);
    }

    /**
     * Create a detached, initialised SimResultRecord
     */
    public SimResultRecord(Long id, Long runId, Long buildId, String targetRole, String targetArmor, BigDecimal targetHp, JSONB targetSkills, Integer targetPoints, BigDecimal dmgPerHit, BigDecimal dpsSustained, BigDecimal dpsBurst, BigDecimal ttkS, BigDecimal hitsToKill, Boolean energyLimited, JSONB extras) {
        super(SimResult.SIM_RESULT);

        setId(id);
        setRunId(runId);
        setBuildId(buildId);
        setTargetRole(targetRole);
        setTargetArmor(targetArmor);
        setTargetHp(targetHp);
        setTargetSkills(targetSkills);
        setTargetPoints(targetPoints);
        setDmgPerHit(dmgPerHit);
        setDpsSustained(dpsSustained);
        setDpsBurst(dpsBurst);
        setTtkS(ttkS);
        setHitsToKill(hitsToKill);
        setEnergyLimited(energyLimited);
        setExtras(extras);
        resetChangedOnNotNull();
    }
}
