/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimRunRecord extends UpdatableRecordImpl<SimRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_run.id</code>.
     */
    public SimRunRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_run.realm</code>.
     */
    public SimRunRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.sim_run.started_at</code>.
     */
    public SimRunRecord setStartedAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.sim_run.finished_at</code>.
     */
    public SimRunRecord setFinishedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.sim_run.trigger</code>.
     */
    public SimRunRecord setTrigger(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.trigger</code>.
     */
    public String getTrigger() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sim_run.engine_version</code>.
     */
    public SimRunRecord setEngineVersion(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.engine_version</code>.
     */
    public String getEngineVersion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.sim_run.config_hash</code>.
     */
    public SimRunRecord setConfigHash(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.config_hash</code>.
     */
    public String getConfigHash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.sim_run.scenario</code>.
     */
    public SimRunRecord setScenario(JSONB value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.scenario</code>.
     */
    public JSONB getScenario() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.sim_run.status</code>.
     */
    public SimRunRecord setStatus(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_run.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimRunRecord
     */
    public SimRunRecord() {
        super(SimRun.SIM_RUN);
    }

    /**
     * Create a detached, initialised SimRunRecord
     */
    public SimRunRecord(Long id, Integer realm, OffsetDateTime startedAt, OffsetDateTime finishedAt, String trigger, String engineVersion, String configHash, JSONB scenario, String status) {
        super(SimRun.SIM_RUN);

        setId(id);
        setRealm(realm);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
        setTrigger(trigger);
        setEngineVersion(engineVersion);
        setConfigHash(configHash);
        setScenario(scenario);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
