/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimTrace;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimTraceRecord extends UpdatableRecordImpl<SimTraceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_trace.id</code>.
     */
    public SimTraceRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_trace.run_id</code>.
     */
    public SimTraceRecord setRunId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sim_trace.build_id</code>.
     */
    public SimTraceRecord setBuildId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.build_id</code>.
     */
    public Long getBuildId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sim_trace.t_ms</code>.
     */
    public SimTraceRecord setTMs(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.t_ms</code>.
     */
    public Long getTMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.sim_trace.event</code>.
     */
    public SimTraceRecord setEvent(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.event</code>.
     */
    public String getEvent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sim_trace.amount</code>.
     */
    public SimTraceRecord setAmount(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimTraceRecord
     */
    public SimTraceRecord() {
        super(SimTrace.SIM_TRACE);
    }

    /**
     * Create a detached, initialised SimTraceRecord
     */
    public SimTraceRecord(Long id, Long runId, Long buildId, Long tMs, String event, BigDecimal amount) {
        super(SimTrace.SIM_TRACE);

        setId(id);
        setRunId(runId);
        setBuildId(buildId);
        setTMs(tMs);
        setEvent(event);
        setAmount(amount);
        resetChangedOnNotNull();
    }
}
