/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq.tables.records;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimTrace;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimTraceRecord extends UpdatableRecordImpl<SimTraceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sim_trace.id</code>.
     */
    public SimTraceRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sim_trace.run_id</code>.
     */
    public SimTraceRecord setRunId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sim_trace.build_id</code>.
     */
    public SimTraceRecord setBuildId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.build_id</code>.
     */
    public Long getBuildId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sim_trace.t_ms</code>.
     */
    public SimTraceRecord setTMs(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.t_ms</code>.
     */
    public Long getTMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.sim_trace.event</code>.
     */
    public SimTraceRecord setEvent(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.event</code>.
     */
    public String getEvent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sim_trace.amount</code>.
     */
    public SimTraceRecord setAmount(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.sim_trace.target_role</code>.
     */
    public SimTraceRecord setTargetRole(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.target_role</code>.
     */
    public String getTargetRole() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.sim_trace.target_armor</code>.
     */
    public SimTraceRecord setTargetArmor(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.target_armor</code>.
     */
    public String getTargetArmor() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.sim_trace.iteration</code>.
     */
    public SimTraceRecord setIteration(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.iteration</code>.
     */
    public Integer getIteration() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.sim_trace.arena_index</code>.
     */
    public SimTraceRecord setArenaIndex(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.arena_index</code>.
     */
    public Integer getArenaIndex() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.sim_trace.tick</code>.
     */
    public SimTraceRecord setTick(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.tick</code>.
     */
    public Integer getTick() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.sim_trace.seq</code>.
     */
    public SimTraceRecord setSeq(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.seq</code>.
     */
    public Integer getSeq() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.sim_trace.actor</code>.
     */
    public SimTraceRecord setActor(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.actor</code>.
     */
    public String getActor() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.sim_trace.raw_amount</code>.
     */
    public SimTraceRecord setRawAmount(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.raw_amount</code>.
     */
    public BigDecimal getRawAmount() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>public.sim_trace.anchor_tick</code>.
     */
    public SimTraceRecord setAnchorTick(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.anchor_tick</code>.
     */
    public Integer getAnchorTick() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.sim_trace.modifiers</code>. Applied damage
     * modifiers for this hit, one object per modifier: source, operator
     * (FLAT|MULTIPLIER), operand, priority, type, reductive. NULL means not
     * captured; [] means captured and empty.
     */
    public SimTraceRecord setModifiers(JSONB value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.sim_trace.modifiers</code>. Applied damage
     * modifiers for this hit, one object per modifier: source, operator
     * (FLAT|MULTIPLIER), operand, priority, type, reductive. NULL means not
     * captured; [] means captured and empty.
     */
    public JSONB getModifiers() {
        return (JSONB) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimTraceRecord
     */
    public SimTraceRecord() {
        super(SimTrace.SIM_TRACE);
    }

    /**
     * Create a detached, initialised SimTraceRecord
     */
    public SimTraceRecord(Long id, Long runId, Long buildId, Long tMs, String event, BigDecimal amount, String targetRole, String targetArmor, Integer iteration, Integer arenaIndex, Integer tick, Integer seq, String actor, BigDecimal rawAmount, Integer anchorTick, JSONB modifiers) {
        super(SimTrace.SIM_TRACE);

        setId(id);
        setRunId(runId);
        setBuildId(buildId);
        setTMs(tMs);
        setEvent(event);
        setAmount(amount);
        setTargetRole(targetRole);
        setTargetArmor(targetArmor);
        setIteration(iteration);
        setArenaIndex(arenaIndex);
        setTick(tick);
        setSeq(seq);
        setActor(actor);
        setRawAmount(rawAmount);
        setAnchorTick(anchorTick);
        setModifiers(modifiers);
        resetChangedOnNotNull();
    }
}
