/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.Content;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContentRecord extends UpdatableRecordImpl<ContentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.content.id</code>.
     */
    public ContentRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.content.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.content.type</code>.
     */
    public ContentRecord setType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.content.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.content.name</code>.
     */
    public ContentRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.content.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.content.description</code>.
     */
    public ContentRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.content.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.content.status</code>.
     */
    public ContentRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.content.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.content.draft</code>.
     */
    public ContentRecord setDraft(JSONB value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.content.draft</code>.
     */
    public JSONB getDraft() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.content.published</code>.
     */
    public ContentRecord setPublished(JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.content.published</code>.
     */
    public JSONB getPublished() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.content.version</code>.
     */
    public ContentRecord setVersion(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.content.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.content.revision</code>.
     */
    public ContentRecord setRevision(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.content.revision</code>.
     */
    public Integer getRevision() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.content.created_at</code>.
     */
    public ContentRecord setCreatedAt(OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.content.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.content.created_by</code>.
     */
    public ContentRecord setCreatedBy(UUID value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.content.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>public.content.updated_at</code>.
     */
    public ContentRecord setUpdatedAt(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.content.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.content.updated_by</code>.
     */
    public ContentRecord setUpdatedBy(UUID value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.content.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>public.content.published_at</code>.
     */
    public ContentRecord setPublishedAt(OffsetDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.content.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.content.published_by</code>.
     */
    public ContentRecord setPublishedBy(UUID value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.content.published_by</code>.
     */
    public UUID getPublishedBy() {
        return (UUID) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentRecord
     */
    public ContentRecord() {
        super(Content.CONTENT);
    }

    /**
     * Create a detached, initialised ContentRecord
     */
    public ContentRecord(UUID id, String type, String name, String description, String status, JSONB draft, JSONB published, Integer version, Integer revision, OffsetDateTime createdAt, UUID createdBy, OffsetDateTime updatedAt, UUID updatedBy, OffsetDateTime publishedAt, UUID publishedBy) {
        super(Content.CONTENT);

        setId(id);
        setType(type);
        setName(name);
        setDescription(description);
        setStatus(status);
        setDraft(draft);
        setPublished(published);
        setVersion(version);
        setRevision(revision);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setPublishedAt(publishedAt);
        setPublishedBy(publishedBy);
        resetChangedOnNotNull();
    }
}
