/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.ContentLinks;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContentLinksRecord extends UpdatableRecordImpl<ContentLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.content_links.from_content_id</code>.
     */
    public ContentLinksRecord setFromContentId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.content_links.from_content_id</code>.
     */
    public UUID getFromContentId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.content_links.to_content_id</code>.
     */
    public ContentLinksRecord setToContentId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.content_links.to_content_id</code>.
     */
    public UUID getToContentId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.content_links.kind</code>.
     */
    public ContentLinksRecord setKind(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.content_links.kind</code>.
     */
    public String getKind() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, UUID, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentLinksRecord
     */
    public ContentLinksRecord() {
        super(ContentLinks.CONTENT_LINKS);
    }

    /**
     * Create a detached, initialised ContentLinksRecord
     */
    public ContentLinksRecord(UUID fromContentId, UUID toContentId, String kind) {
        super(ContentLinks.CONTENT_LINKS);

        setFromContentId(fromContentId);
        setToContentId(toContentId);
        setKind(kind);
        resetChangedOnNotNull();
    }
}
