/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.ContentSnapshots;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContentSnapshotsRecord extends UpdatableRecordImpl<ContentSnapshotsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.content_snapshots.id</code>.
     */
    public ContentSnapshotsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.content_snapshots.content_id</code>.
     */
    public ContentSnapshotsRecord setContentId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.content_id</code>.
     */
    public UUID getContentId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.content_snapshots.version</code>.
     */
    public ContentSnapshotsRecord setVersion(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.content_snapshots.payload</code>.
     */
    public ContentSnapshotsRecord setPayload(JSONB value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.content_snapshots.label</code>.
     */
    public ContentSnapshotsRecord setLabel(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.label</code>.
     */
    public String getLabel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.content_snapshots.created_at</code>.
     */
    public ContentSnapshotsRecord setCreatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.content_snapshots.created_by</code>.
     */
    public ContentSnapshotsRecord setCreatedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.content_snapshots.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentSnapshotsRecord
     */
    public ContentSnapshotsRecord() {
        super(ContentSnapshots.CONTENT_SNAPSHOTS);
    }

    /**
     * Create a detached, initialised ContentSnapshotsRecord
     */
    public ContentSnapshotsRecord(UUID id, UUID contentId, Integer version, JSONB payload, String label, OffsetDateTime createdAt, UUID createdBy) {
        super(ContentSnapshots.CONTENT_SNAPSHOTS);

        setId(id);
        setContentId(contentId);
        setVersion(version);
        setPayload(payload);
        setLabel(label);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
