/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GameProfessions;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameProfessionsRecord extends UpdatableRecordImpl<GameProfessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_professions.key</code>.
     */
    public GameProfessionsRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_professions.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.game_professions.display_name</code>.
     */
    public GameProfessionsRecord setDisplayName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_professions.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.game_professions.max_level</code>.
     */
    public GameProfessionsRecord setMaxLevel(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game_professions.max_level</code>.
     */
    public Integer getMaxLevel() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameProfessionsRecord
     */
    public GameProfessionsRecord() {
        super(GameProfessions.GAME_PROFESSIONS);
    }

    /**
     * Create a detached, initialised GameProfessionsRecord
     */
    public GameProfessionsRecord(String key, String displayName, Integer maxLevel) {
        super(GameProfessions.GAME_PROFESSIONS);

        setKey(key);
        setDisplayName(displayName);
        setMaxLevel(maxLevel);
        resetChangedOnNotNull();
    }
}
