/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GameZones;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameZonesRecord extends UpdatableRecordImpl<GameZonesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_zones.key</code>.
     */
    public GameZonesRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_zones.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.game_zones.display_name</code>.
     */
    public GameZonesRecord setDisplayName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_zones.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.game_zones.world</code>.
     */
    public GameZonesRecord setWorld(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game_zones.world</code>.
     */
    public String getWorld() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.game_zones.tags</code>.
     */
    public GameZonesRecord setTags(String[] value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.game_zones.tags</code>.
     */
    public String[] getTags() {
        return (String[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameZonesRecord
     */
    public GameZonesRecord() {
        super(GameZones.GAME_ZONES);
    }

    /**
     * Create a detached, initialised GameZonesRecord
     */
    public GameZonesRecord(String key, String displayName, String world, String[] tags) {
        super(GameZones.GAME_ZONES);

        setKey(key);
        setDisplayName(displayName);
        setWorld(world);
        setTags(tags);
        resetChangedOnNotNull();
    }
}
