/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GameNpcFactories;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameNpcFactoriesRecord extends UpdatableRecordImpl<GameNpcFactoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_npc_factories.factory</code>.
     */
    public GameNpcFactoriesRecord setFactory(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_npc_factories.factory</code>.
     */
    public String getFactory() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.game_npc_factories.type</code>.
     */
    public GameNpcFactoriesRecord setType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_npc_factories.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameNpcFactoriesRecord
     */
    public GameNpcFactoriesRecord() {
        super(GameNpcFactories.GAME_NPC_FACTORIES);
    }

    /**
     * Create a detached, initialised GameNpcFactoriesRecord
     */
    public GameNpcFactoriesRecord(String factory, String type) {
        super(GameNpcFactories.GAME_NPC_FACTORIES);

        setFactory(factory);
        setType(type);
        resetChangedOnNotNull();
    }
}
