/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GameItems;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameItemsRecord extends UpdatableRecordImpl<GameItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_items.key</code>.
     */
    public GameItemsRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_items.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.game_items.display_name</code>.
     */
    public GameItemsRecord setDisplayName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_items.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.game_items.source</code>.
     */
    public GameItemsRecord setSource(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game_items.source</code>.
     */
    public String getSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.game_items.material</code>.
     */
    public GameItemsRecord setMaterial(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.game_items.material</code>.
     */
    public String getMaterial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.game_items.tags</code>.
     */
    public GameItemsRecord setTags(String[] value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.game_items.tags</code>.
     */
    public String[] getTags() {
        return (String[]) get(4);
    }

    /**
     * Setter for <code>public.game_items.updated_at</code>.
     */
    public GameItemsRecord setUpdatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.game_items.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameItemsRecord
     */
    public GameItemsRecord() {
        super(GameItems.GAME_ITEMS);
    }

    /**
     * Create a detached, initialised GameItemsRecord
     */
    public GameItemsRecord(String key, String displayName, String source, String material, String[] tags, OffsetDateTime updatedAt) {
        super(GameItems.GAME_ITEMS);

        setKey(key);
        setDisplayName(displayName);
        setSource(source);
        setMaterial(material);
        setTags(tags);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
