/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.PurityRuneSlotDistributions;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurityRuneSlotDistributionsRecord extends UpdatableRecordImpl<PurityRuneSlotDistributionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purity_rune_slot_distributions.purity</code>.
     */
    public PurityRuneSlotDistributionsRecord setPurity(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_rune_slot_distributions.purity</code>.
     */
    public String getPurity() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.purity_rune_slot_distributions.draft</code>.
     */
    public PurityRuneSlotDistributionsRecord setDraft(JSONB value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_rune_slot_distributions.draft</code>.
     */
    public JSONB getDraft() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.purity_rune_slot_distributions.published</code>.
     */
    public PurityRuneSlotDistributionsRecord setPublished(JSONB value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_rune_slot_distributions.published</code>.
     */
    public JSONB getPublished() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.purity_rune_slot_distributions.updated_at</code>.
     */
    public PurityRuneSlotDistributionsRecord setUpdatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_rune_slot_distributions.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for
     * <code>public.purity_rune_slot_distributions.published_at</code>.
     */
    public PurityRuneSlotDistributionsRecord setPublishedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.purity_rune_slot_distributions.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurityRuneSlotDistributionsRecord
     */
    public PurityRuneSlotDistributionsRecord() {
        super(PurityRuneSlotDistributions.PURITY_RUNE_SLOT_DISTRIBUTIONS);
    }

    /**
     * Create a detached, initialised PurityRuneSlotDistributionsRecord
     */
    public PurityRuneSlotDistributionsRecord(String purity, JSONB draft, JSONB published, OffsetDateTime updatedAt, OffsetDateTime publishedAt) {
        super(PurityRuneSlotDistributions.PURITY_RUNE_SLOT_DISTRIBUTIONS);

        setPurity(purity);
        setDraft(draft);
        setPublished(published);
        setUpdatedAt(updatedAt);
        setPublishedAt(publishedAt);
        resetChangedOnNotNull();
    }
}
