/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.PurityReforgeBias;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurityReforgeBiasRecord extends UpdatableRecordImpl<PurityReforgeBiasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purity_reforge_bias.purity</code>.
     */
    public PurityReforgeBiasRecord setPurity(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_reforge_bias.purity</code>.
     */
    public String getPurity() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.purity_reforge_bias.draft</code>.
     */
    public PurityReforgeBiasRecord setDraft(JSONB value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_reforge_bias.draft</code>.
     */
    public JSONB getDraft() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.purity_reforge_bias.published</code>.
     */
    public PurityReforgeBiasRecord setPublished(JSONB value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_reforge_bias.published</code>.
     */
    public JSONB getPublished() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.purity_reforge_bias.updated_at</code>.
     */
    public PurityReforgeBiasRecord setUpdatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_reforge_bias.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.purity_reforge_bias.published_at</code>.
     */
    public PurityReforgeBiasRecord setPublishedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_reforge_bias.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurityReforgeBiasRecord
     */
    public PurityReforgeBiasRecord() {
        super(PurityReforgeBias.PURITY_REFORGE_BIAS);
    }

    /**
     * Create a detached, initialised PurityReforgeBiasRecord
     */
    public PurityReforgeBiasRecord(String purity, JSONB draft, JSONB published, OffsetDateTime updatedAt, OffsetDateTime publishedAt) {
        super(PurityReforgeBias.PURITY_REFORGE_BIAS);

        setPurity(purity);
        setDraft(draft);
        setPublished(published);
        setUpdatedAt(updatedAt);
        setPublishedAt(publishedAt);
        resetChangedOnNotNull();
    }
}
