/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.PurityDistributions;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurityDistributionsRecord extends UpdatableRecordImpl<PurityDistributionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purity_distributions.name</code>.
     */
    public PurityDistributionsRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_distributions.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.purity_distributions.draft</code>.
     */
    public PurityDistributionsRecord setDraft(JSONB value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_distributions.draft</code>.
     */
    public JSONB getDraft() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.purity_distributions.published</code>.
     */
    public PurityDistributionsRecord setPublished(JSONB value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_distributions.published</code>.
     */
    public JSONB getPublished() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.purity_distributions.updated_at</code>.
     */
    public PurityDistributionsRecord setUpdatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_distributions.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.purity_distributions.published_at</code>.
     */
    public PurityDistributionsRecord setPublishedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.purity_distributions.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurityDistributionsRecord
     */
    public PurityDistributionsRecord() {
        super(PurityDistributions.PURITY_DISTRIBUTIONS);
    }

    /**
     * Create a detached, initialised PurityDistributionsRecord
     */
    public PurityDistributionsRecord(String name, JSONB draft, JSONB published, OffsetDateTime updatedAt, OffsetDateTime publishedAt) {
        super(PurityDistributions.PURITY_DISTRIBUTIONS);

        setName(name);
        setDraft(draft);
        setPublished(published);
        setUpdatedAt(updatedAt);
        setPublishedAt(publishedAt);
        resetChangedOnNotNull();
    }
}
