/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.QuestInstances;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestInstancesRecord extends UpdatableRecordImpl<QuestInstancesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quest_instances.id</code>.
     */
    public QuestInstancesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.quest_instances.quest_id</code>.
     */
    public QuestInstancesRecord setQuestId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.quest_id</code>.
     */
    public String getQuestId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quest_instances.scope_type</code>.
     */
    public QuestInstancesRecord setScopeType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.scope_type</code>.
     */
    public String getScopeType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.quest_instances.scope_id</code>.
     */
    public QuestInstancesRecord setScopeId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.quest_instances.status</code>.
     */
    public QuestInstancesRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.quest_instances.current_stages</code>.
     */
    public QuestInstancesRecord setCurrentStages(JSONB value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.current_stages</code>.
     */
    public JSONB getCurrentStages() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.quest_instances.started_at</code>.
     */
    public QuestInstancesRecord setStartedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.quest_instances.updated_at</code>.
     */
    public QuestInstancesRecord setUpdatedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_instances.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestInstancesRecord
     */
    public QuestInstancesRecord() {
        super(QuestInstances.QUEST_INSTANCES);
    }

    /**
     * Create a detached, initialised QuestInstancesRecord
     */
    public QuestInstancesRecord(UUID id, String questId, String scopeType, String scopeId, String status, JSONB currentStages, OffsetDateTime startedAt, OffsetDateTime updatedAt) {
        super(QuestInstances.QUEST_INSTANCES);

        setId(id);
        setQuestId(questId);
        setScopeType(scopeType);
        setScopeId(scopeId);
        setStatus(status);
        setCurrentStages(currentStages);
        setStartedAt(startedAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
