/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.QuestFlags;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestFlagsRecord extends UpdatableRecordImpl<QuestFlagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quest_flags.scope_type</code>.
     */
    public QuestFlagsRecord setScopeType(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_flags.scope_type</code>.
     */
    public String getScopeType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.quest_flags.scope_id</code>.
     */
    public QuestFlagsRecord setScopeId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_flags.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quest_flags.flag</code>.
     */
    public QuestFlagsRecord setFlag(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_flags.flag</code>.
     */
    public String getFlag() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.quest_flags.value</code>.
     */
    public QuestFlagsRecord setValue(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_flags.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestFlagsRecord
     */
    public QuestFlagsRecord() {
        super(QuestFlags.QUEST_FLAGS);
    }

    /**
     * Create a detached, initialised QuestFlagsRecord
     */
    public QuestFlagsRecord(String scopeType, String scopeId, String flag, String value) {
        super(QuestFlags.QUEST_FLAGS);

        setScopeType(scopeType);
        setScopeId(scopeId);
        setFlag(flag);
        setValue(value);
        resetChangedOnNotNull();
    }
}
