/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.QuestObjectiveProgress;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestObjectiveProgressRecord extends UpdatableRecordImpl<QuestObjectiveProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quest_objective_progress.instance_id</code>.
     */
    public QuestObjectiveProgressRecord setInstanceId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_objective_progress.instance_id</code>.
     */
    public UUID getInstanceId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.quest_objective_progress.objective_key</code>.
     */
    public QuestObjectiveProgressRecord setObjectiveKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_objective_progress.objective_key</code>.
     */
    public String getObjectiveKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quest_objective_progress.progress</code>.
     */
    public QuestObjectiveProgressRecord setProgress(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_objective_progress.progress</code>.
     */
    public Integer getProgress() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.quest_objective_progress.target</code>.
     */
    public QuestObjectiveProgressRecord setTarget(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_objective_progress.target</code>.
     */
    public Integer getTarget() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestObjectiveProgressRecord
     */
    public QuestObjectiveProgressRecord() {
        super(QuestObjectiveProgress.QUEST_OBJECTIVE_PROGRESS);
    }

    /**
     * Create a detached, initialised QuestObjectiveProgressRecord
     */
    public QuestObjectiveProgressRecord(UUID instanceId, String objectiveKey, Integer progress, Integer target) {
        super(QuestObjectiveProgress.QUEST_OBJECTIVE_PROGRESS);

        setInstanceId(instanceId);
        setObjectiveKey(objectiveKey);
        setProgress(progress);
        setTarget(target);
        resetChangedOnNotNull();
    }
}
