/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.QuestNpcs;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestNpcsRecord extends UpdatableRecordImpl<QuestNpcsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quest_npcs.id</code>.
     */
    public QuestNpcsRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.quest_npcs.display_name</code>.
     */
    public QuestNpcsRecord setDisplayName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quest_npcs.source</code>.
     */
    public QuestNpcsRecord setSource(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.source</code>.
     */
    public String getSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.quest_npcs.factory</code>.
     */
    public QuestNpcsRecord setFactory(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.factory</code>.
     */
    public String getFactory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.quest_npcs.type</code>.
     */
    public QuestNpcsRecord setType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.quest_npcs.skin_value</code>.
     */
    public QuestNpcsRecord setSkinValue(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.skin_value</code>.
     */
    public String getSkinValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.quest_npcs.skin_signature</code>.
     */
    public QuestNpcsRecord setSkinSignature(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.skin_signature</code>.
     */
    public String getSkinSignature() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.quest_npcs.updated_at</code>.
     */
    public QuestNpcsRecord setUpdatedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_npcs.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestNpcsRecord
     */
    public QuestNpcsRecord() {
        super(QuestNpcs.QUEST_NPCS);
    }

    /**
     * Create a detached, initialised QuestNpcsRecord
     */
    public QuestNpcsRecord(String id, String displayName, String source, String factory, String type, String skinValue, String skinSignature, OffsetDateTime updatedAt) {
        super(QuestNpcs.QUEST_NPCS);

        setId(id);
        setDisplayName(displayName);
        setSource(source);
        setFactory(factory);
        setType(type);
        setSkinValue(skinValue);
        setSkinSignature(skinSignature);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
