/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.QuestPrimitives;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuestPrimitivesRecord extends UpdatableRecordImpl<QuestPrimitivesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quest_primitives.id</code>.
     */
    public QuestPrimitivesRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_primitives.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.quest_primitives.category</code>.
     */
    public QuestPrimitivesRecord setCategory(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_primitives.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quest_primitives.label</code>.
     */
    public QuestPrimitivesRecord setLabel(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_primitives.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.quest_primitives.param_schema</code>.
     */
    public QuestPrimitivesRecord setParamSchema(JSONB value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_primitives.param_schema</code>.
     */
    public JSONB getParamSchema() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.quest_primitives.ui</code>.
     */
    public QuestPrimitivesRecord setUi(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.quest_primitives.ui</code>.
     */
    public JSONB getUi() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestPrimitivesRecord
     */
    public QuestPrimitivesRecord() {
        super(QuestPrimitives.QUEST_PRIMITIVES);
    }

    /**
     * Create a detached, initialised QuestPrimitivesRecord
     */
    public QuestPrimitivesRecord(String id, String category, String label, JSONB paramSchema, JSONB ui) {
        super(QuestPrimitives.QUEST_PRIMITIVES);

        setId(id);
        setCategory(category);
        setLabel(label);
        setParamSchema(paramSchema);
        setUi(ui);
        resetChangedOnNotNull();
    }
}
