/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.ZoneDiscoveries;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ZoneDiscoveriesRecord extends UpdatableRecordImpl<ZoneDiscoveriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.zone_discoveries.id</code>.
     */
    public ZoneDiscoveriesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.zone_discoveries.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.zone_discoveries.client</code>.
     */
    public ZoneDiscoveriesRecord setClient(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.zone_discoveries.client</code>.
     */
    public Long getClient() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.zone_discoveries.zone_id</code>.
     */
    public ZoneDiscoveriesRecord setZoneId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.zone_discoveries.zone_id</code>.
     */
    public Long getZoneId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.zone_discoveries.discovered_at</code>.
     */
    public ZoneDiscoveriesRecord setDiscoveredAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.zone_discoveries.discovered_at</code>.
     */
    public LocalDateTime getDiscoveredAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZoneDiscoveriesRecord
     */
    public ZoneDiscoveriesRecord() {
        super(ZoneDiscoveries.ZONE_DISCOVERIES);
    }

    /**
     * Create a detached, initialised ZoneDiscoveriesRecord
     */
    public ZoneDiscoveriesRecord(Long id, Long client, Long zoneId, LocalDateTime discoveredAt) {
        super(ZoneDiscoveries.ZONE_DISCOVERIES);

        setId(id);
        setClient(client);
        setZoneId(zoneId);
        setDiscoveredAt(discoveredAt);
        resetChangedOnNotNull();
    }
}
