/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.Zones;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ZonesRecord extends UpdatableRecordImpl<ZonesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.zones.id</code>.
     */
    public ZonesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.zones.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.zones.zone_key</code>.
     */
    public ZonesRecord setZoneKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.zones.zone_key</code>.
     */
    public String getZoneKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.zones.display_name</code>.
     */
    public ZonesRecord setDisplayName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.zones.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZonesRecord
     */
    public ZonesRecord() {
        super(Zones.ZONES);
    }

    /**
     * Create a detached, initialised ZonesRecord
     */
    public ZonesRecord(Long id, String zoneKey, String displayName) {
        super(Zones.ZONES);

        setId(id);
        setZoneKey(zoneKey);
        setDisplayName(displayName);
        resetChangedOnNotNull();
    }
}
