/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimDuelDiagnostic;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimResult;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimTrace;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.sim_build</code>.
     */
    public final SimBuild SIM_BUILD = SimBuild.SIM_BUILD;

    /**
     * The table <code>public.sim_duel_diagnostic</code>.
     */
    public final SimDuelDiagnostic SIM_DUEL_DIAGNOSTIC = SimDuelDiagnostic.SIM_DUEL_DIAGNOSTIC;

    /**
     * The table <code>public.sim_result</code>.
     */
    public final SimResult SIM_RESULT = SimResult.SIM_RESULT;

    /**
     * The table <code>public.sim_run</code>.
     */
    public final SimRun SIM_RUN = SimRun.SIM_RUN;

    /**
     * The table <code>public.sim_trace</code>.
     */
    public final SimTrace SIM_TRACE = SimTrace.SIM_TRACE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SimBuild.SIM_BUILD,
            SimDuelDiagnostic.SIM_DUEL_DIAGNOSTIC,
            SimResult.SIM_RESULT,
            SimRun.SIM_RUN,
            SimTrace.SIM_TRACE
        );
    }
}
