/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.balancesim.database.jooq;


import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimBuild;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimDuelDiagnostic;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimResult;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimRun;
import me.mykindos.betterpvp.balancesim.database.jooq.tables.SimTrace;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.sim_build</code>.
     */
    public static final SimBuild SIM_BUILD = SimBuild.SIM_BUILD;

    /**
     * The table <code>public.sim_duel_diagnostic</code>.
     */
    public static final SimDuelDiagnostic SIM_DUEL_DIAGNOSTIC = SimDuelDiagnostic.SIM_DUEL_DIAGNOSTIC;

    /**
     * The table <code>public.sim_result</code>.
     */
    public static final SimResult SIM_RESULT = SimResult.SIM_RESULT;

    /**
     * The table <code>public.sim_run</code>.
     */
    public static final SimRun SIM_RUN = SimRun.SIM_RUN;

    /**
     * The table <code>public.sim_trace</code>.
     */
    public static final SimTrace SIM_TRACE = SimTrace.SIM_TRACE;
}
